plugins.push(new VRN());

function VRN(){
  var now = new Date();
  var busData;
  var BUS_API = "81a322e8-9e2b-485f-88de-6d14a0525613";

  function loadData(object){
    var busurl = "http://efa9-5.vrn.de/dm_rbl/XSLT_DM_REQUEST?itdLPxx_dmlayout=vrn&itdLPxx_realtime=1&limit=4&useRealtime=1&depType=stopEvents&typeInfo_dm=stopID&nameInfo_dm="+(6000000+Math.round(persistent.get("stop_id")))+"&mode=direct";
    var busapi_url = "https://api.import.io/store/data/"+BUS_API+"/_query?input/webpage/url="+encodeURIComponent(busurl)+"&_user=e2eb28a4-f0c6-4b15-946c-4b933cd2d167&_apikey="+API_KEY;
    $.get(busapi_url,function(data){
      busData = data;
      console.log(busData);
      processBus(object);
    });

  }

  function getOptions(){
    var result = '';
    result += '<div class="content-box">';
    result += ' <div class="form-box swap-order">';
		result += '   <div class="autofill-box" id="autofill_stop">';
		result += '     <div class="autofill">';
		result += '       <ul>';
		result += '					<li id="autofill_stop_1"></li>';
		result += '					<li id="autofill_stop_2"></li>';
		result += '					<li id="autofill_stop_3"></li>';
		result += '				</ul>';
		result += '			</div>';
		result += '		</div>';
    result += '   <input id="haltestelle" placeholder="Haltestelle" />';
    result += '   <label for="haltestelle">VRN Haltestelle</label>';
		result += '	</div>';
    result += ' <div class="form-box">';
    result += '   <span class="label">ID</span>';
    result += '   <span class="haltestellenid input"></span>';
    result += ' </div>';
    result += '</div>';
    return result;
  }

    function processBus(object){
    var data = busData;
    var items = persistent.get("stop");

    var stopName = "Fahrplan";
    if(items.hasOwnProperty("stop")) {
      stopName = items.stop;
    }

    var result = '<div class="list-box" id="busplan"><ul>';
    result += '<li data-role="list-divider">'+stopName+'</li>';
    for(key in data.results) {
      result += '<li><div class="item-icon-wrapper"><div class="item-icon">';
      if(data.results[key].icon.endsWith("bus.png")) {// || data.results[key].icon.endsWith("s_bahn.png") || data.results[key].icon.endsWith("ice.png") || data.results[key].icon.endsWith("regionalbahn.png")) {
        // bus icon
        result += '<svg style="width:24px;height:24px" viewBox="0 0 24 24"><path fill="#999999" d="M18,11H6V6H18M16.5,17A1.5,1.5 0 0,1 15,15.5A1.5,1.5 0 0,1 16.5,14A1.5,1.5 0 0,1 18,15.5A1.5,1.5 0 0,1 16.5,17M7.5,17A1.5,1.5 0 0,1 6,15.5A1.5,1.5 0 0,1 7.5,14A1.5,1.5 0 0,1 9,15.5A1.5,1.5 0 0,1 7.5,17M4,16C4,16.88 4.39,17.67 5,18.22V20A1,1 0 0,0 6,21H7A1,1 0 0,0 8,20V19H16V20A1,1 0 0,0 17,21H18A1,1 0 0,0 19,20V18.22C19.61,17.67 20,16.88 20,16V6C20,2.5 16.42,2 12,2C7.58,2 4,2.5 4,6V16Z" /></svg>';
      } else {
        // tram icon
        result += '<svg style="width:24px;height:24px" viewBox="0 0 24 24"><path fill="#999999" d="M18,10H6V5H18M12,17C10.89,17 10,16.1 10,15C10,13.89 10.89,13 12,13A2,2 0 0,1 14,15A2,2 0 0,1 12,17M4,15.5A3.5,3.5 0 0,0 7.5,19L6,20.5V21H18V20.5L16.5,19A3.5,3.5 0 0,0 20,15.5V5C20,1.5 16.42,1 12,1C7.58,1 4,1.5 4,5V15.5Z" /></svg>';
      }
      result += '</div><div class="flex-box">';
      result += '<span><strong>'+data.results[key].abfahrt+'</strong>';
      if(data.results[key].hasOwnProperty('time')) {

        var colorClass = 'color-red';
        if(data.results[key].time.endsWith("nktlich"))
          colorClass = 'color-green';

        result += ' <span class="'+colorClass+'">'+data.results[key].time+'</span>';
      }
      result += '<br>'+data.results[key].direction+'</span>';
      result += ' <span>'+data.results[key].linie+'</span>';
      result += '</div>';
      result += '</div></li>';
    }
    result += '</ul></div>';
    $(object).html(result);
  }

  function search(array,term){

    var result = [];
    for(var  i = 0 ; i < array.length ; i++){
      if (decodeHtml(array[i].hs).toLowerCase().indexOf(term.toLowerCase())>-1) {
        result.push(array[i]);
      }
    }
    return result;

  }

  function changeStation(){
    console.log("changeStation");
      var value = $("#haltestelle").val();
      var result = search(vrn,value);
      if(value === "" || (decodeHtml(result[0].hs) == value)){
        $("#autofill_stop").slideUp();
        if(result.length == 1){
          $(".haltestellenid").text(result[0].value);
          persistent.set({"stop": decodeHtml(result[0].hs), "stop_id":result[0].value});
          setupPlugins();
        }
      }
      else{
        if(result.length > 0){
            $("#autofill_stop").slideDown();
            $("#autofill_stop_1").slideDown();
            $("#autofill_stop_1").html(result[0].hs);
        }
        else{
          $("#autofill_stop").slideUp();
        }
        if(result.length > 1){
          $("#autofill_stop_2").slideDown();
          $("#autofill_stop_2").html(result[1].hs);
        }
        else{
          $("#autofill_stop_2").slideUp();
        }
        if(result.length > 2){
          $("#autofill_stop_3").slideDown();
          $("#autofill_stop_3").html(result[2].hs);
        }
        else{
          $("#autofill_stop_3").slideUp();
        }
      }
  }
  function listeners(){
    $("#haltestelle").on("keyup",changeStation);
    $(".autofill li").on("click",autofill);
  }

  function autofill(){
    $("#haltestelle").val($( this ).html());
    changeStation();
  }


  return {
    setup : function(object){
      console.log("setupVRN");
      this.setHtmlAt(object);
    },
    option : function(){
      console.log("optionsVRN");
      return getOptions();
    },
    setHtmlAt : function(object){
      console.log("reloadHTML");
      loadData(object);
    },
    getPriority : function(){
      return 1;
    },
    createListener : function(){
      listeners();
    }


  }
}

var vrn = [
{hs:"Alsheim, Bahnhof",value:15},
{hs:"Altleiningen, Feuerwehr",value:20},
{hs:"Altlu&szlig;heim, Quelle",value:34},
{hs:"Altlu&szlig;heim, Hauptstra&szlig;e 111",value:35},
{hs:"Altlu&szlig;heim, Lu&szlig;hof/Rheinbr&uuml;cke",value:36},
{hs:"Altlu&szlig;heim, Raiffeisenbank",value:37},
{hs:"Altlu&szlig;heim, Rebst&ouml;ckl",value:38},
{hs:"Altrip, Hartmann",value:45},
{hs:"Altrip, Goethestra&szlig;e",value:46},
{hs:"Altrip, Ludwigsplatz",value:47},
{hs:"Altrip, Maxburgstra&szlig;e",value:48},
{hs:"Altrip, F&auml;hre",value:50},
{hs:"Neckarau, F&auml;hre",value:51},
{hs:"Altlu&szlig;heim, Altreut",value:86},
{hs:"Bad D&uuml;rkheim, Amtsgericht",value:112},
{hs:"Bad D&uuml;rkheim, Bahnhof",value:116},
{hs:"Bad D&uuml;rkheim, Ost",value:134},
{hs:"Bad D&uuml;rkheim, Schulzent. Trift",value:140},
{hs:"Beindersheim, Schule",value:219},
{hs:"Beindersheim, Mitte",value:225},
{hs:"Beindersheim, Siedlung",value:226},
{hs:"Beindersheim, S&uuml;d",value:227},
{hs:"Bensheim, Bahnhof",value:236},
{hs:"Auerbach, Bahnhof",value:248},
{hs:"Biblis, Bahnhof",value:270},
{hs:"Birkenheide, Alb.-Scherer-Str.",value:316},
{hs:"Birkenheide, Bruchgewanne",value:317},
{hs:"Birkenheide, Sachsenstra&szlig;e",value:319},
{hs:"Birkenheide, Schule",value:320},
{hs:"Bissersheim, Friedhof",value:325},
{hs:"Bissersheim, Siegel",value:326},
{hs:"Bobenheim, Anton-Bruckner-Str.",value:335},
{hs:"Bobenheim, Bahnhof",value:336},
{hs:"Bobenheim, Kirche",value:337},
{hs:"Bobenheim, Schule",value:338},
{hs:"Bobenheim, Nord",value:339},
{hs:"Bobenheim, Ostring",value:340},
{hs:"Bobenheim, Frankenthaler Str.",value:341},
{hs:"Bobenheim, Siedlung",value:342},
{hs:"Roxheim, Berliner Stra&szlig;e",value:344},
{hs:"Roxheim, Bratzler",value:345},
{hs:"Roxheim, Marktplatz",value:346},
{hs:"Roxheim, M&ouml;rscher Stra&szlig;e",value:347},
{hs:"Roxheim, Postamt",value:348},
{hs:"Roxheim, Rathaus",value:349},
{hs:"Roxheim, R&ouml;ntgenstra&szlig;e",value:350},
{hs:"Roxheim, Theodor-Heuss-Stra&szlig;e",value:351},
{hs:"Bockenheim, Mitte",value:360},
{hs:"Bockenheim, Neuh&auml;usel",value:361},
{hs:"Bockenheim, Winzersch&auml;nke",value:363},
{hs:"B&ouml;hl-Iggelheim, Bahnhof",value:373},
{hs:"Iggelheim, Haardtstra&szlig;e",value:374},
{hs:"Iggelheim, Kreissparkasse",value:375},
{hs:"Iggelheim, Rehbachstra&szlig;e",value:378},
{hs:"Br&uuml;hl, Drogerie Hartmann",value:390},
{hs:"Br&uuml;hl, Ketscher Stra&szlig;e",value:392},
{hs:"Br&uuml;hl, Mannheimer Stra&szlig;e",value:393},
{hs:"Br&uuml;hl, Messplatz",value:394},
{hs:"Br&uuml;hl, Nibelungenstra&szlig;e",value:395},
{hs:"Br&uuml;hl, Schwetzinger Stra&szlig;e",value:397},
{hs:"Br&uuml;hl, Schwimmbad",value:398},
{hs:"Br&uuml;hl, Siedlung",value:399},
{hs:"Br&uuml;hl, Wiesengrund",value:400},
{hs:"Rohrhof, Br&uuml;hler Stra&szlig;e",value:401},
{hs:"Rohrhof, Lessingstra&szlig;e",value:402},
{hs:"Bobstadt, Bahnhof",value:410},
{hs:"B&uuml;rstadt, Bahnhof",value:416},
{hs:"Carlsberg, Lei&szlig;linger Platz",value:435},
{hs:"Carlsberg, Brunnenstra&szlig;e",value:436},
{hs:"Carlsberg, Finkenhof",value:437},
{hs:"Carlsberg, Gartenstra&szlig;e",value:438},
{hs:"Carlsberg, Linienstra&szlig;e",value:439},
{hs:"Carlsberg, Sonnenberg",value:440},
{hs:"Carlsberg, Neuhof",value:443},
{hs:"Dannstadt, Albrecht-D&uuml;rer-Str.",value:450},
{hs:"Dannstadt, Apotheke",value:451},
{hs:"Dannstadt, Friedhof",value:453},
{hs:"Dannstadt, Kirchenstra&szlig;e",value:454},
{hs:"Dannstadt, Ludwigshafener Str.",value:455},
{hs:"Dannstadt, Weinbietstra&szlig;e",value:459},
{hs:"Schauernheim, Mitte",value:460},
{hs:"Schauernheim, Nord",value:461},
{hs:"Schauernheim, S&uuml;d",value:462},
{hs:"Deidesheim, Bahnhof",value:470},
{hs:"Beindersheim, Ost",value:488},
{hs:"Dirmstein, Kirche",value:495},
{hs:"Dirmstein, Ost",value:496},
{hs:"Dirmstein, Schule",value:497},
{hs:"Dirmstein, Siedlung",value:498},
{hs:"Dossenheim, Bahnhof",value:515},
{hs:"Dossenheim, S&uuml;d",value:516},
{hs:"Eberbach, Bahnhof",value:534},
{hs:"Lindach, Bahnhof",value:574},
{hs:"Ebertsheim, Bahnhof",value:609},
{hs:"Ebertsheim, Friedhof",value:610},
{hs:"Rodenbach, Ort",value:613},
{hs:"Edingen, Ost",value:616},
{hs:"Neckarhausen, Thomas-Mann-Str.",value:617},
{hs:"Edingen, Bahnhof",value:619},
{hs:"Edingen, Pf&auml;lzer Hof",value:620},
{hs:"Edingen, Rathaus",value:621},
{hs:"Edingen, Schillerstra&szlig;e",value:622},
{hs:"Edingen, West",value:623},
{hs:"Neckarhausen, Br&uuml;cke",value:624},
{hs:"Neckarhausen, Ost",value:625},
{hs:"Neckarhausen, Rathaus",value:626},
{hs:"Neckarhausen, West",value:627},
{hs:"Neu-Edingen, Ahornstra&szlig;e",value:628},
{hs:"Neu-Edingen, Gewerbegebiet",value:629},
{hs:"Neu-Edingen, Breslauer Stra&szlig;e",value:630},
{hs:"Neu-Edingen, Lilienstra&szlig;e",value:631},
{hs:"Ellerstadt, Akaziensiedlung",value:655},
{hs:"Ellerstadt, Ost",value:656},
{hs:"Ellerstadt, Raiffeisen",value:657},
{hs:"Ellerstadt, West",value:658},
{hs:"Ellerstadt, Kreissparkasse",value:659},
{hs:"Ellerstadt, Feuerwehr",value:682},
{hs:"Eppelheim, Jakobsgasse",value:695},
{hs:"Eppelheim, Kirchheimer Stra&szlig;e",value:696},
{hs:"Eppelheim, Rathaus",value:697},
{hs:"Forst, Sportplatz",value:746},
{hs:"Forst, Waage",value:747},
{hs:"Eppstein, Kirche",value:761},
{hs:"Eppstein, Leininger Stra&szlig;e",value:762},
{hs:"Eppstein, S&uuml;d",value:763},
{hs:"Eppstein, West",value:764},
{hs:"Flomersheim, Bahnhof",value:765},
{hs:"Flomersheim, Gemeindehaus",value:767},
{hs:"Flomersheim, Siedlung",value:769},
{hs:"Frankenthal, Albr.-D&uuml;rer-Ring",value:770},
{hs:"Frankenthal, Hauptbahnhof",value:771},
{hs:"Frankenthal, Einkaufsz. Nord",value:772},
{hs:"Frankenthal, Beindersheimer S.",value:773},
{hs:"Frankenthal, Benderstra&szlig;e",value:774},
{hs:"Frankenthal, Bosch-Siedlung",value:775},
{hs:"Frankenthal, Europaring",value:776},
{hs:"Frankenthal, Feierabendhaus",value:778},
{hs:"Frankenthal, Friedhof",value:780},
{hs:"Frankenthal, Ganghofer Stra&szlig;e",value:781},
{hs:"Frankenthal (Pfalz), Altenheim",value:783},
{hs:"Frankenthal, Jahnplatz",value:784},
{hs:"Frankenthal, K.-Kollwitz-Str.",value:785},
{hs:"Frankenthal, KKK",value:786},
{hs:"Frankenthal, Stadtklinik",value:787},
{hs:"Frankenthal, Ludwigshafener S.",value:789},
{hs:"Frankenthal, Neumayerschule",value:790},
{hs:"Frankenthal, Nordring",value:792},
{hs:"Frankenthal, Parsevalplatz",value:794},
{hs:"Frankenthal, Pilgerstra&szlig;e",value:795},
{hs:"Frankenthal, R.-Schuman-Schule",value:796},
{hs:"Frankenthal, Schillerschule",value:797},
{hs:"Frankenthal, Speyerer Tor",value:798},
{hs:"Frankenthal, Stadtwerke",value:799},
{hs:"Frankenthal, Waldorfschule",value:804},
{hs:"Frankenthal, Wormser Tor",value:806},
{hs:"M&ouml;rsch, Ahornstra&szlig;e",value:807},
{hs:"M&ouml;rsch, Am Nu&szlig;baum",value:808},
{hs:"M&ouml;rsch, Schule",value:809},
{hs:"M&ouml;rsch, S&uuml;d",value:810},
{hs:"Studernheim, Friedhof",value:812},
{hs:"Studernheim, Kirche",value:813},
{hs:"Frankenthal, Adenauerplatz",value:815},
{hs:"Frankenthal, Philipp-Rauch-Str",value:818},
{hs:"Frankenthal, Nord",value:819},
{hs:"Studernheim, S&uuml;d",value:820},
{hs:"Frankenthal, Uhlandstra&szlig;e",value:821},
{hs:"Frankenthal, Johann-Klein-Str.",value:822},
{hs:"Frankenthal, Schmiedgasse",value:823},
{hs:"Frankenthal, Altenheim",value:824},
{hs:"Frankenthal, ADR Kiosk",value:825},
{hs:"Frankenthal, Beckmannstra&szlig;e",value:826},
{hs:"Frankenthal, Paul-Klee-Stra&szlig;e",value:827},
{hs:"Frankenthal, Schongauer Stra&szlig;e",value:828},
{hs:"Frankenthal, Dan.-Bechtel-Str.",value:830},
{hs:"Frankenthal (Pfalz), Hammstra&szlig;",value:831},
{hs:"Frankenthal, Robert-Bosch-Str.",value:832},
{hs:"Frankenthal, Mannheimer Stra&szlig;e",value:833},
{hs:"Br&uuml;hl, Seniorenzentrum",value:834},
{hs:"Eppstein, H&auml;ndelstra&szlig;e",value:835},
{hs:"Eppstein, Johann-Strau&szlig;-Stra&szlig;e",value:836},
{hs:"Freinsheim, Bahnhof",value:840},
{hs:"Frankenthal, Zeppelinstra&szlig;e",value:842},
{hs:"Friedelsheim, Beck",value:855},
{hs:"Friedelsheim, Bahnhof",value:856},
{hs:"Friedelsheim, Winzergenossens.",value:858},
{hs:"Fu&szlig;g&ouml;nheim, Bahnhof",value:910},
{hs:"Fu&szlig;g&ouml;nheim, Bahnhofstra&szlig;e",value:911},
{hs:"Gerolsheim, Mitte",value:925},
{hs:"Gerolsheim, Siedlung",value:926},
{hs:"G&ouml;nnheim, Bahnhof",value:940},
{hs:"G&ouml;nnheim, Waage",value:941},
{hs:"R&ouml;dersheim, Kirche",value:980},
{hs:"R&ouml;dersheim, Kreuz",value:981},
{hs:"R&ouml;dersheim, Ost",value:982},
{hs:"R&ouml;dersheim, West",value:983},
{hs:"Gro&szlig;-Rohrheim, Bahnhof",value:990},
{hs:"Gro&szlig;karlbach, Bahnhof",value:995},
{hs:"Gro&szlig;karlbach, Kirche",value:996},
{hs:"Gro&szlig;niedesheim, Mitte",value:1000},
{hs:"Gro&szlig;niedesheim, Siedlung",value:1001},
{hs:"Asselheim, Bahnhof",value:1003},
{hs:"Asselheim, Abzw. Bockenheim",value:1005},
{hs:"Asselheim, Abzw. Eisenberg",value:1006},
{hs:"Asselheim, Siedlung",value:1008},
{hs:"Gr&uuml;nstadt, Bahnhof",value:1009},
{hs:"Gr&uuml;nstadt, Depot",value:1010},
{hs:"Gr&uuml;nstadt, Didier",value:1011},
{hs:"Gr&uuml;nstadt, Bahnhof Nord",value:1012},
{hs:"Gr&uuml;nstadt, Schulzentrum",value:1013},
{hs:"Gr&uuml;nstadt, Heiner",value:1014},
{hs:"Gr&uuml;nstadt, Industriegebiet",value:1015},
{hs:"Gr&uuml;nstadt, Peterspark",value:1016},
{hs:"Gr&uuml;nstadt, Turnhalle",value:1018},
{hs:"Gr&uuml;nstadt, Dekan-Ernst-Schule",value:1025},
{hs:"Gr&uuml;nstadt, Verbandsgemeinde",value:1027},
{hs:"Ha&szlig;loch, Bahnhof",value:1080},
{hs:"Ha&szlig;loch, Grohe",value:1082},
{hs:"Ha&szlig;loch, Hauck",value:1085},
{hs:"Ha&szlig;loch, Schillerschule",value:1092},
{hs:"Ha&szlig;loch, Storchen",value:1095},
{hs:"Ha&szlig;loch, Rotkreuzhaus",value:1097},
{hs:"Heddesheim-Hirschberg, Bf DB",value:1110},
{hs:"Heddesheim, Blumenstra&szlig;e",value:1111},
{hs:"Heddesheim, Gewerbegebiet",value:1112},
{hs:"Heddesheim, Rathaus",value:1114},
{hs:"Heddesheim, Siedlung",value:1115},
{hs:"Handschuhsheim, Biethsstra&szlig;e",value:1132},
{hs:"Handschuhsheim, Burgstra&szlig;e",value:1133},
{hs:"Handschuhsheim, Kapellenweg",value:1135},
{hs:"Handschuhsheim, H.-Thoma-Pl.",value:1136},
{hs:"Heidelberg, Bismarckplatz",value:1146},
{hs:"Heidelberg, Hauptbahnhof",value:1160},
{hs:"Heidelberg, Altstadt",value:1166},
{hs:"Heidelberg, Ochsenkopf",value:1180},
{hs:"Heidelberg, Poststra&szlig;e",value:1183},
{hs:"Heidelberg, Stadtb&uuml;cherei",value:1193},
{hs:"Heidelberg, Stadtwerke",value:1194},
{hs:"Kirchheim/Rohrbach",value:1203},
{hs:"Kirchheim, Pleikartsf&ouml;rst. Hof",value:1210},
{hs:"Kirchheim, Kurpfalzhof",value:1212},
{hs:"Neuenheim, Blumenthalstra&szlig;e",value:1225},
{hs:"Neuenheim, Ku&szlig;maulstra&szlig;e",value:1233},
{hs:"Neuenheim, Br&uuml;ckenstra&szlig;e",value:1260},
{hs:"Pfaffengrund, Stotz",value:1261},
{hs:"Schlierbach, Orthop&auml;dische Kl.",value:1284},
{hs:"Schlierbach-Ziegelhausen, Bhf",value:1287},
{hs:"Wieblingen, Mitte",value:1302},
{hs:"Wieblingen, Taubenfeld",value:1304},
{hs:"Heidelberg, Gneisenaustr. S&uuml;d",value:1330},
{hs:"Heidelberg, Berufsschule",value:1331},
{hs:"HD-Pfaffengrund/Wieblingen",value:1454},
{hs:"Heidelberg, S-Bf. Weststadt/S&uuml;",value:1457},
{hs:"Hemsbach, Bahnhof",value:1471},
{hs:"Heppenheim, Bahnhof",value:1502},
{hs:"Hertlingshausen",value:1545},
{hs:"Herxheim a.B., Bahnhof",value:1553},
{hs:"He&szlig;heim, Alte Post",value:1555},
{hs:"He&szlig;heim, Mitte",value:1556},
{hs:"He&szlig;heim, Siedlung",value:1557},
{hs:"He&szlig;heim, Sippel",value:1558},
{hs:"Hettenleidelheim, Poststra&szlig;e",value:1565},
{hs:"Hettenleidelh,Tiefenthaler Str",value:1566},
{hs:"Hettenleidelh,Brunnenwiesenstr",value:1567},
{hs:"Hettenleidelheim, Turnhalle",value:1569},
{hs:"Speyer, Dudenhofer Stra&szlig;e",value:1574},
{hs:"Heuchelheim, Ort",value:1575},
{hs:"Gro&szlig;sachsen, Bahnhof",value:1581},
{hs:"Gro&szlig;sachsen, Rose",value:1582},
{hs:"Gro&szlig;sachsen, Talsiedlung",value:1583},
{hs:"Leutershausen, Heddesh. Stra&szlig;e",value:1584},
{hs:"Leutershausen, Bahnhof",value:1585},
{hs:"Leutershausen, West",value:1586},
{hs:"Hirschhorn, Bahnhof",value:1590},
{hs:"Hochdorf, M&uuml;hle",value:1598},
{hs:"Assenheim, Bundesstra&szlig;e",value:1605},
{hs:"Assenheim, Friedhof",value:1606},
{hs:"Assenheim, Kurze Stra&szlig;e",value:1607},
{hs:"Assenheim, R&ouml;merbrunnen",value:1608},
{hs:"Hochdorf, Kirche",value:1609},
{hs:"Hochdorf, Schule",value:1610},
{hs:"Hochdorf, Siedlung",value:1611},
{hs:"Hochdorf, West",value:1612},
{hs:"Hockenheim, Bahnhof",value:1620},
{hs:"Hockenheim, H.-von-Kleist-Str.",value:1621},
{hs:"Hockenheim, Kaiserstra&szlig;e",value:1622},
{hs:"Hockenheim, Rathaus",value:1623},
{hs:"Hockenheim, &Uuml;berf&uuml;hrungstra&szlig;e",value:1624},
{hs:"Talhaus, 1.Industriestra&szlig;e",value:1625},
{hs:"Talhaus, 2.Industriestra&szlig;e",value:1626},
{hs:"Talhaus, 4.Industriestra&szlig;e",value:1627},
{hs:"Talhaus, Hardtbachbr&uuml;cke",value:1628},
{hs:"Talhaus, S&uuml;pag",value:1629},
{hs:"Ilvesheim, Deidesheimer Stra&szlig;e",value:1640},
{hs:"Ilvesheim, H.-Vetter-Stift",value:1641},
{hs:"Ilvesheim, Lange Morgen",value:1642},
{hs:"Ilvesheim, Rathaus",value:1643},
{hs:"Ilvesheim, Neue Schulstra&szlig;e",value:1644},
{hs:"Ilvesheim, Uferstra&szlig;e",value:1645},
{hs:"Ilvesheim, West",value:1654},
{hs:"Frankenthal, Adamslust",value:1658},
{hs:"Ketsch, Albrecht",value:1660},
{hs:"Ketsch, Bahnhof",value:1661},
{hs:"Ketsch, Gartenstra&szlig;e",value:1662},
{hs:"Ketsch, Karlsruher Stra&szlig;e",value:1663},
{hs:"Ketsch, Gewerbegebiet S&uuml;d",value:1664},
{hs:"Ketsch, Schillerplatz",value:1665},
{hs:"Gerolsheim, Untergasse",value:1666},
{hs:"Gerolsheim, Gartenstra&szlig;e",value:1667},
{hs:"Ketsch, Waldsportplatz",value:1668},
{hs:"Gerolsheim, Ost",value:1677},
{hs:"Kindenheim, Schneider",value:1682},
{hs:"Kindenheim, Untere Hauptstra&szlig;e",value:1683},
{hs:"Kindenheim, Mitte",value:1684},
{hs:"Kirchheim/Wstr., Bahnhof",value:1685},
{hs:"Kirchheim/Wstr., Ort",value:1686},
{hs:"Kirchheim/Wstr., Pfeiffer",value:1687},
{hs:"Kirchheim/Wstr., Schule",value:1688},
{hs:"Kirchheim, Im B&uuml;gen",value:1690},
{hs:"Heidelberg, Fachhochschule",value:1693},
{hs:"Kleinniedesheim, Gemeindehaus",value:1705},
{hs:"Kleinniedesheim, Wendestelle",value:1706},
{hs:"Kleinniedesheim, R&ouml;merstra&szlig;e",value:1707},
{hs:"Kleinniedesheim, Am Schlo&szlig;",value:1708},
{hs:"Ladenburg, Bahnhof",value:1711},
{hs:"Ladenburg, Benzstra&szlig;e",value:1712},
{hs:"Ladenburg, Carl-Benz-Platz",value:1713},
{hs:"Ladenburg, Ilvesheimer Stra&szlig;e",value:1714},
{hs:"Ladenburg, Kanalbr&uuml;cke",value:1715},
{hs:"Ladenburg, Martinstor",value:1716},
{hs:"Ladenburg, Rautenthaler M&uuml;hle",value:1718},
{hs:"Ladenburg, Rosenhof",value:1719},
{hs:"Ladenburg, Ruckelshausen",value:1720},
{hs:"Ladenburg, Schwarzkreuzstra&szlig;e",value:1721},
{hs:"Ladenburg, Wallstadter Stra&szlig;e",value:1722},
{hs:"Ladenburg, Ankerplatz",value:1726},
{hs:"Ladenburg, Domitianstra&szlig;e",value:1727},
{hs:"Ladenburg, Jupiterplatz",value:1729},
{hs:"Lambrecht, Bahnhof",value:1730},
{hs:"Ladenburg, Weiherg&auml;rten",value:1734},
{hs:"Ladenburg, Am Kandelbach",value:1739},
{hs:"Heddesheim, J-Kepler-Schule",value:1743},
{hs:"Lambsheim, Bahnhof",value:1745},
{hs:"Heddesheim, Sportzentrum",value:1754},
{hs:"Hofheim, Bahnhof",value:1757},
{hs:"Lampertheim, Bahnhof",value:1771},
{hs:"Lampertheim, Ernst-Ludwig-Str.",value:1772},
{hs:"Lampertheim, E.-Schreiber-Str.",value:1775},
{hs:"Lampertheim, Europabr&uuml;cke",value:1776},
{hs:"Lampertheim, Glefsweilerstra&szlig;e",value:1777},
{hs:"Lampertheim, Hallenbad",value:1781},
{hs:"Lampertheim, Mannheimer Stra&szlig;e",value:1783},
{hs:"Lampertheim, Neuschlo&szlig;stra&szlig;e",value:1784},
{hs:"Lampertheim, Friedhof",value:1786},
{hs:"Lampertheim, Sandtorfer Weg",value:1789},
{hs:"Lampertheim, Stadion",value:1792},
{hs:"Lampertheim, Schillerplatz",value:1802},
{hs:"Lampertheim, Anne-Frank-Stra&szlig;e",value:1806},
{hs:"Lampertheim, Bertha-Benz-Weg",value:1807},
{hs:"Lampertheim, Amselstra&szlig;e",value:1808},
{hs:"Lampertheim, Biedensand",value:1809},
{hs:"Frankenthal, KSB",value:1813},
{hs:"Laudenbach, Bahnhof",value:1825},
{hs:"Laumersheim, Kirche",value:1840},
{hs:"Laumersheim, Nord",value:1841},
{hs:"Laumersheim, Schule",value:1842},
{hs:"St. Ilgen, Bahnhof",value:1892},
{hs:"Limburgerhof, Bahnhof",value:1917},
{hs:"Limburgerhof, Berliner Platz",value:1919},
{hs:"Limburgerhof, Burgunder Platz",value:1920},
{hs:"Limburgerhof, Carl-Bosch-Sch.",value:1921},
{hs:"Limburgerhof, Einsteinallee",value:1923},
{hs:"Limburgerhof, Fichtestra&szlig;e",value:1924},
{hs:"Limburgerhof, Mainzer Stra&szlig;e",value:1927},
{hs:"Limburgerhof, Messplatz",value:1928},
{hs:"Limburgerhof, M&uuml;hlweg",value:1929},
{hs:"Limburgerhof, Neuhofener Str.",value:1931},
{hs:"Limburgerhof, Speyerer Stra&szlig;e",value:1933},
{hs:"Limburgerhof, S&uuml;d",value:1934},
{hs:"Limburgerhof, Tilsiter Stra&szlig;e",value:1935},
{hs:"Limburgerhof, Max-Planck-Str.",value:1937},
{hs:"Limburgerhof, Trifelsr./Agrarz",value:1939},
{hs:"Ladenburg, Weststadt",value:1980},
{hs:"Gr&uuml;nstadt, Obers&uuml;lzer Stra&szlig;e",value:2004},
{hs:"Gro&szlig;karlbach, Osterberg",value:2009},
{hs:"Ludwigshafen, Mitte",value:2019},
{hs:"Edigheim, Anglerstra&szlig;e",value:2021},
{hs:"Edigheim, Bruderweg",value:2022},
{hs:"Edigheim, Deichstra&szlig;e",value:2023},
{hs:"Edigheim, Kirche",value:2024},
{hs:"Edigheim, Im Zinkig",value:2025},
{hs:"Edigheim, Kranichstra&szlig;e",value:2026},
{hs:"Edigheim, R&uuml;digerstra&szlig;e",value:2027},
{hs:"Edigheim, Wolfsgrube",value:2028},
{hs:"Friesenheim, Ebertp./Fichtestr",value:2029},
{hs:"Friesenheim, Ost",value:2031},
{hs:"Friesenheim, Lagewiesenstra&szlig;e",value:2033},
{hs:"Friesenh., Rheinfeldstr./Tor 3",value:2035},
{hs:"Friesenheim, Riedsaumpark",value:2036},
{hs:"Friesenheim, Rottst&uuml;ckerweg",value:2037},
{hs:"Friesenheim, Saarbr&uuml;cker Str.",value:2039},
{hs:"Friesenheim, Schopenh. (AWETA)",value:2040},
{hs:"Friesenheim, Schwalbenweg",value:2041},
{hs:"Friesenheim, Sternstra&szlig;e",value:2042},
{hs:"Gartenstadt, Abteistra&szlig;e",value:2043},
{hs:"Gartenstadt, Hochfeldstra&szlig;e",value:2044},
{hs:"Gartenstadt, Kallstadter Str.",value:2045},
{hs:"Gartenstadt, K&ouml;nigsbacher Str.",value:2046},
{hs:"Gartenstadt, Leininger Stra&szlig;e",value:2047},
{hs:"Gartenstadt, Marienkrankenhaus",value:2048},
{hs:"Gartenstadt, Von-Kieffer-Str.",value:2049},
{hs:"Gartenstadt, Pommernstra&szlig;e",value:2050},
{hs:"Gartenstadt, Schlesierstra&szlig;e",value:2051},
{hs:"Gartenstadt, Volkshaus",value:2052},
{hs:"Friesenheim, Ammoniakstra&szlig;e",value:2053},
{hs:"Ludwigshafen, Arbeitsamt",value:2056},
{hs:"Ludwigshafen, BASF (Tor 1+2)",value:2060},
{hs:"Edigheim, Friedhof",value:2061},
{hs:"Ludwigshafen, BASF Tor 11",value:2062},
{hs:"Ludwigshafen, BASF Tor 12",value:2063},
{hs:"Ludwigshafen, BASF Tor 5",value:2065},
{hs:"Ludwigshafen, Berliner Platz",value:2066},
{hs:"Ludwigshafen, Bgm.-Krafft-Pl.",value:2067},
{hs:"Ludwigshafen, Bgm.-Kutterer-S.",value:2068},
{hs:"Ludwigshafen, Bruchwiesenstr.",value:2069},
{hs:"Ludwigshafen, Feierabendhaus",value:2073},
{hs:"Ludwigshafen, Gartenstra&szlig;e",value:2074},
{hs:"Ludwigshafen, Goerdelerplatz",value:2075},
{hs:"Ludwigshafen, Gro&szlig;e Blies",value:2076},
{hs:"Ludwigshafen, W.-Hack-Museum",value:2077},
{hs:"Ludwigshafen, Halberg",value:2078},
{hs:"Ludwigshafen, Klinikum",value:2079},
{hs:"Ludwigshafen, Hauptbahnhof",value:2080},
{hs:"Ludwigshafen, Hauptfriedhof",value:2081},
{hs:"Ludwigshafen, Hauptbahnh. ZOB",value:2082},
{hs:"Ludwigshafen, He.-Pesch-Haus",value:2083},
{hs:"Ludwigshafen, Hemshofstra&szlig;e",value:2084},
{hs:"Ludwigshafen, J&auml;gerstra&szlig;e",value:2085},
{hs:"Ludwigshafen, K.-Wilhelm-Str.",value:2086},
{hs:"Ludwigshafen, BASF Tor 12 Busb",value:2088},
{hs:"Ludwigshafen, Ludwigstra&szlig;e",value:2089},
{hs:"Ludwigshafen, Marienkirche",value:2090},
{hs:"Gartenstadt, Ebereschenweg",value:2092},
{hs:"Ludwigshafen, Pfalzb./W.Hack.",value:2093},
{hs:"Oggersheim, Fieskostra&szlig;e",value:2094},
{hs:"Ludwigshafen, Raschig",value:2095},
{hs:"Ludwigshafen, Rathaus",value:2096},
{hs:"Ludwigshafen, Rhein-Galerie",value:2097},
{hs:"Ludwigshafen, Bayreuther Str.",value:2098},
{hs:"Ludwigshafen, Rohrlachstra&szlig;e",value:2100},
{hs:"Friesenheim, Mitte",value:2102},
{hs:"Ludwigshafen, Sch&uuml;tzenstra&szlig;e",value:2104},
{hs:"Ludwigshafen, Shellhaus",value:2105},
{hs:"Kirchheim, Elementary School",value:2107},
{hs:"Ludwigshafen, S&uuml;dwest-Stadion",value:2108},
{hs:"Ludwigshafen, Val.-Bauer-Sied.",value:2109},
{hs:"Ludwigshafen, Val.-Bauer-Sied.",value:2110},
{hs:"Ludwigshafen, Wittelsbachplatz",value:2111},
{hs:"Ludwigshafen, Hein.-Ries-Halle",value:2112},
{hs:"Maudach, Ortsmitte",value:2115},
{hs:"Maudach, Gemeindehaus",value:2117},
{hs:"Gartenstadt, K&auml;rntner Stra&szlig;e",value:2118},
{hs:"Maudach, Krappstra&szlig;e",value:2119},
{hs:"Maudach, Endstelle",value:2120},
{hs:"Mundenheim, Maudacher Stra&szlig;e",value:2121},
{hs:"Maudach, Ortseingang",value:2122},
{hs:"Gartenstadt, Maudacher Bruch",value:2123},
{hs:"Mundenheim, Achtmorgenstra&szlig;e",value:2124},
{hs:"Mundenheim, Am Schwanen",value:2125},
{hs:"Ludwigshafen, Friedenspark",value:2126},
{hs:"LU-Mundenheim, Bahnhof",value:2127},
{hs:"Mundenheim, Feuerwache",value:2129},
{hs:"Mundenheim, Friedhof",value:2130},
{hs:"Mundenheim, Giulini",value:2132},
{hs:"Mundenheim, Stifterstra&szlig;e",value:2133},
{hs:"Mundenheim, Hoheneckenstra&szlig;e",value:2134},
{hs:"Mundenheim, K.-Burger-Str.",value:2135},
{hs:"Mundenheim, Kaiserw&ouml;rthdamm",value:2136},
{hs:"Mundenheim, Knappenwegstra&szlig;e",value:2137},
{hs:"Mundenheim, Nord",value:2139},
{hs:"Mundenheim, Schillerschule",value:2141},
{hs:"Oggersheim, Wollstra&szlig;e",value:2142},
{hs:"Niederfeld, Damaschkestra&szlig;e",value:2144},
{hs:"Niederfeld",value:2145},
{hs:"Oggersheim, Adolf-Kolping-Str.",value:2146},
{hs:"Oggersheim, Am Weidenschlag",value:2147},
{hs:"LU-Oggersheim, Bahnhof",value:2148},
{hs:"Oggersheim, Bexbacher Stra&szlig;e",value:2149},
{hs:"Oggersheim, Buschwegbr&uuml;cke",value:2150},
{hs:"Ludwigshafen, Pettenkoferstr.",value:2151},
{hs:"Oggersheim, Friedhof",value:2152},
{hs:"Oggersheim, Froschlache",value:2153},
{hs:"Oggersheim, Hans-Warsch-Pl.",value:2154},
{hs:"Oggersheim, Hollerg&auml;rten",value:2155},
{hs:"Oggersheim, Im Schelmenhersch.",value:2156},
{hs:"Oggersheim, Mannheimer Tor",value:2157},
{hs:"Oggersheim, Notwende",value:2158},
{hs:"Oggersheim, IGSLO",value:2159},
{hs:"Oggersheim, Rheinhorststra&szlig;e",value:2160},
{hs:"Oggersheim, Rosenw&ouml;rthstra&szlig;e",value:2161},
{hs:"Oggersheim, Speyerer Stra&szlig;e",value:2162},
{hs:"Oggersheim, Uferstra&szlig;e",value:2163},
{hs:"Oggersheim, BG Unfallklinik",value:2164},
{hs:"Oggersheim, Wilhelm-Tell-Str.",value:2165},
{hs:"Oggersheim, Zum Guten Hirten",value:2166},
{hs:"Oppau, B&uuml;rgerm.-Zorn-Platz",value:2168},
{hs:"Oppau, Dammbruchstra&szlig;e",value:2169},
{hs:"Oppau, Frankenstra&szlig;e",value:2170},
{hs:"Oppau, Gemeindehaus",value:2171},
{hs:"Oppau, Horst-Schork-Stra&szlig;e",value:2172},
{hs:"Oppau, Kirchenstra&szlig;e",value:2173},
{hs:"Oppau, Kurt-Schumacher-Stra&szlig;e",value:2174},
{hs:"Oppau, S&uuml;d (BASF Q 920)",value:2176},
{hs:"Melm, K.-Dillinger-Stra&szlig;e",value:2177},
{hs:"Oppau, West",value:2178},
{hs:"Edigheim, Ostringplatz",value:2179},
{hs:"Oppau, Endstelle",value:2181},
{hs:"Oppau, St&uuml;tzelstra&szlig;e",value:2182},
{hs:"Pfingstweide, Br&uuml;sseler Ring",value:2185},
{hs:"Melm, H.-Schifferdecker-Stra&szlig;e",value:2186},
{hs:"Pfingstweide, Zentrum",value:2187},
{hs:"LU Rheing&ouml;nheim, Bahnhof",value:2189},
{hs:"Rheing&ouml;nheim, Br&uuml;ckweg",value:2191},
{hs:"Rheing&ouml;nheim, Friedensstra&szlig;e",value:2192},
{hs:"Oggersheim, D&uuml;rkheimer Stra&szlig;e",value:2194},
{hs:"Rheing&ouml;nheim, Kief'scher Weih.",value:2195},
{hs:"Rheing&ouml;nheim, Rehbach",value:2196},
{hs:"Rheing&ouml;nheim, Endstelle",value:2197},
{hs:"Rheing&ouml;nheim, Waldm&uuml;hle",value:2198},
{hs:"Rheing&ouml;nheim, Wei&szlig;es H&auml;us'l",value:2199},
{hs:"Rheing&ouml;nheim, Wildpark",value:2200},
{hs:"Ruchheim, Am H&uuml;ttengraben",value:2201},
{hs:"Ruchheim, Schloss",value:2202},
{hs:"Ruchheim",value:2203},
{hs:"Ruchheim, Baustra&szlig;e",value:2206},
{hs:"BASF, L440 Weststra&szlig;e",value:2208},
{hs:"Ludwigshafen, BASF Tor 7",value:2213},
{hs:"Ludwigshafen, Bliesstra&szlig;e",value:2218},
{hs:"Ludwigshafen, BASF S&uuml;d",value:2219},
{hs:"Ruchheim, Am Herrschaftsweiher",value:2230},
{hs:"Ludwigshafen, Pasadenaallee",value:2231},
{hs:"BASF, Tor 7/B9 Anilinfabrikstr",value:2248},
{hs:"Melm, Albert-Haueisen-Ring",value:2255},
{hs:"Mannheim, Fahrlach",value:2258},
{hs:"BASF, Tor 12/T509 Trichterstr.",value:2261},
{hs:"BASF, Tor 12/T410 Trichterstr.",value:2273},
{hs:"BASF, L306 Weststra&szlig;e",value:2280},
{hs:"Feudenheim, A.-Damaschke-Ring",value:2311},
{hs:"Feudenheim, Am Aubuckel",value:2312},
{hs:"Feudenheim, Andreas-Hofer-Str.",value:2313},
{hs:"Feudenheim, Feldstra&szlig;e",value:2314},
{hs:"Feudenheim, Endstelle",value:2315},
{hs:"Feudenheim, H&ouml;lderlinstra&szlig;e",value:2316},
{hs:"Feudenheim, Kirche",value:2317},
{hs:"Feudenheim, Kreuz",value:2318},
{hs:"Feudenheim, Liebfrauenstra&szlig;e",value:2319},
{hs:"Feudenheim, Neckarplatt",value:2320},
{hs:"Feudenheim, Neckarstra&szlig;e",value:2321},
{hs:"Rheinau, Am Rheinauer See",value:2323},
{hs:"Feudenheim, Talstra&szlig;e",value:2324},
{hs:"Feudenheim, Ziethenstra&szlig;e",value:2325},
{hs:"Friedrichsfeld, Alteichwalds.",value:2326},
{hs:"Friedrichsfeld (MA), Elsa-Br&auml;n",value:2327},
{hs:"Friedrichsfeld, Langlachweg",value:2328},
{hs:"Friedrichsfeld, M&uuml;lhauser Str",value:2329},
{hs:"Friedrichsfeld, Neudorfstra&szlig;e",value:2330},
{hs:"MA-Friedrichsfeld, Bahnhof",value:2331},
{hs:"Rheinau, Rotterdamer Str.Nord",value:2332},
{hs:"Friedrichsfeld, L-Gr&auml;ber-Halle",value:2333},
{hs:"MA-Friedrichsfeld, S&uuml;dbahnhof",value:2334},
{hs:"Friedrichsfeld, Vogesenstra&szlig;e",value:2335},
{hs:"Friedrichsfeld, Friedr. Kreuz",value:2336},
{hs:"Friesenheimer Insel, Bastion",value:2337},
{hs:"Fries. Insel, D&uuml;rstelschlag",value:2338},
{hs:"Friesen. Insel, Einsteinstra&szlig;e",value:2339},
{hs:"Fries. Insel, BASF Fries.Insel",value:2340},
{hs:"Fries. Insel, Max-Born-Stra&szlig;e",value:2341},
{hs:"Fries. Insel, Kammerschleuse",value:2342},
{hs:"Rheinau, Rotterdamer Str.Mitte",value:2343},
{hs:"Fries. Insel, Max-Planck-Str.",value:2344},
{hs:"Fries. Insel, Niederweid",value:2345},
{hs:"Friesenheimer Insel, &Ouml;lhafen",value:2346},
{hs:"Friesenh. Insel, &Ouml;lhafenstra&szlig;e",value:2347},
{hs:"Fries. Insel, Rheinrottstra&szlig;e",value:2348},
{hs:"Rheinau, Riedwiesen",value:2349},
{hs:"Fries. Insel, Muskatorm&uuml;hle",value:2350},
{hs:"Fries. Insel, Weidenw&ouml;rth",value:2351},
{hs:"K&auml;fertal, ABB Tor 8",value:2352},
{hs:"K&auml;fertal, Am Kuhbuckel",value:2353},
{hs:"Fries. Insel, Heizkraftwerk No",value:2354},
{hs:"K&auml;fertal, &Auml;u&szlig;ere Wingertstra&szlig;e",value:2355},
{hs:"MA-K&auml;fertal, DB-Bahnhof",value:2356},
{hs:"Mannheim, Lanzvilla",value:2357},
{hs:"K&auml;fertal, Bensheimer Stra&szlig;e",value:2358},
{hs:"K&auml;fertal, Boveristra&szlig;e",value:2359},
{hs:"Neuhermsheim, Thomashaus",value:2360},
{hs:"K&auml;fertal, Friedhof",value:2361},
{hs:"K&auml;fertal, Frohe Arbeit",value:2362},
{hs:"K&auml;fertal, Habichtplatz",value:2363},
{hs:"Mannheim, Kutzerweiher",value:2364},
{hs:"K&auml;fertal, Jugendverkehrsschule",value:2365},
{hs:"Mannheim, Maximilianstra&szlig;e",value:2366},
{hs:"K&auml;fertal, Wald",value:2367},
{hs:"K&auml;fertal, Kometenweg",value:2368},
{hs:"K&auml;fertal, Neues Leben",value:2369},
{hs:"K&auml;fertal, Oskar-v.-Miller-Str.",value:2370},
{hs:"K&auml;fertal, Rathaus",value:2371},
{hs:"K&auml;fertal, Reichenbachstra&szlig;e",value:2372},
{hs:"K&auml;fertal, K&auml;fertalschule",value:2373},
{hs:"K&auml;fertal, Sonnenschein",value:2374},
{hs:"K&auml;fertal, Stiller Weg",value:2375},
{hs:"K&auml;fertal, S&uuml;d",value:2376},
{hs:"Friedrichsfeld, Gebweilerstr.",value:2377},
{hs:"K&auml;fertal, Wachenheimer Stra&szlig;e",value:2378},
{hs:"K&auml;fertal, Z&auml;her Wille",value:2379},
{hs:"Mannheim, Pyramidenstra&szlig;e",value:2380},
{hs:"Sandhofen, F&auml;hre",value:2381},
{hs:"Sandhofen, Amselstra&szlig;e",value:2382},
{hs:"Lindenhof, Lindenhofplatz",value:2383},
{hs:"Lindenhof, Meer&auml;ckerplatz",value:2384},
{hs:"Friesenh. Insel, Gh. Dehus",value:2385},
{hs:"Luzenberg",value:2386},
{hs:"Luzenberg, Mercedes-Benz T.1",value:2387},
{hs:"Luzenberg, Diffenébr&uuml;cke",value:2388},
{hs:"Neckarau, Soldnerstra&szlig;e",value:2389},
{hs:"Rheinau, Stolzeneckstra&szlig;e",value:2390},
{hs:"Luzenberg, Stolberger Stra&szlig;e",value:2391},
{hs:"Rheinau, Sporw&ouml;rthplatz",value:2392},
{hs:"Mannheim, Am Oberen Luisenp.",value:2393},
{hs:"Neckarau, Tannh&auml;userring",value:2394},
{hs:"Mannheim, Am Friedrichsplatz",value:2395},
{hs:"Sandhofen, Jakobuskirche",value:2396},
{hs:"Mannheim, Bgm.-Fuchs-Stra&szlig;e",value:2397},
{hs:"Mannheim, Bibienastra&szlig;e",value:2398},
{hs:"Mannheim, Bonadiesstra&szlig;e",value:2399},
{hs:"Mannheim, Bunsenstra&szlig;e",value:2400},
{hs:"Mannheim, Kunstverein",value:2401},
{hs:"Mannheim, Dalbergstra&szlig;e",value:2402},
{hs:"Mannheim, Dudenstra&szlig;e",value:2403},
{hs:"Mannheim, Exerzierplatz",value:2404},
{hs:"Mannheim, Jungbuschschule",value:2405},
{hs:"Mannheim, Fernmeldeturm",value:2406},
{hs:"Sandhofen, Gro&szlig;-Gerauer Stra&szlig;e",value:2408},
{hs:"Mannheim, Friedrich-K&ouml;nig-Str.",value:2409},
{hs:"Mannheim, Carl-Benz-Stra&szlig;e",value:2410},
{hs:"Mannheim, Gesamtsch.Herzogenr.",value:2411},
{hs:"Mannheim, Gewerkschaftshaus",value:2412},
{hs:"Mannheim, Grenadierstra&szlig;e",value:2413},
{hs:"Mannheim, Gutenbergstra&szlig;e",value:2414},
{hs:"Mannheim, G&uuml;teramt",value:2415},
{hs:"MA-Handelshafen",value:2416},
{hs:"Mannheim, Hauptbahnhof",value:2417},
{hs:"Mannheim, Hauptfriedhof",value:2418},
{hs:"Mannheim, Hauptg&uuml;terbahnhof",value:2419},
{hs:"Rheinau, Konrad-Duden-Schule",value:2420},
{hs:"Mannheim, Herzogenriedstra&szlig;e",value:2421},
{hs:"Mannheim, Hochuferstra&szlig;e",value:2422},
{hs:"Fries. Insel, Hombuschstra&szlig;e",value:2423},
{hs:"Mannheim, Ida-Scipio-Heim",value:2424},
{hs:"Mannheim, Jungbuschbr&uuml;cke",value:2425},
{hs:"Mannheim, Kon.-Adenauer-Br&uuml;cke",value:2426},
{hs:"Mannheim, Kurpfalzbr&uuml;cke",value:2427},
{hs:"Mannheim, Luisenp./Technoseum",value:2429},
{hs:"Mannheim, Landg&uuml;terhalle",value:2430},
{hs:"Mannheim, Landwehrstra&szlig;e",value:2431},
{hs:"Mannheim, Lange R&ouml;tterstra&szlig;e",value:2432},
{hs:"Mannheim, Lessingstra&szlig;e",value:2433},
{hs:"Mannheim, Lortzingstra&szlig;e",value:2435},
{hs:"Mannheim, Zielstra&szlig;e",value:2437},
{hs:"Mannheim, Marktplatz",value:2438},
{hs:"Mannheim, Max-Joseph-Stra&szlig;e",value:2439},
{hs:"Mannheim, M&ouml;hlstra&szlig;e",value:2440},
{hs:"Mannheim, Eisenlohrstra&szlig;e",value:2441},
{hs:"Mannheim, Moselstra&szlig;e",value:2442},
{hs:"Mannheim, M&uuml;hldorferstra&szlig;e",value:2443},
{hs:"Mannheim, Nationaltheater",value:2444},
{hs:"Mannheim, Neckarspitze",value:2445},
{hs:"Neckarstadt West",value:2446},
{hs:"Mannheim, Abendakademie",value:2447},
{hs:"Mannheim, Neckarvorlandstra&szlig;e",value:2448},
{hs:"Mannheim, Neuer Me&szlig;platz",value:2449},
{hs:"Mannheim, Otto-Beck-Stra&szlig;e",value:2450},
{hs:"Mannheim, Paradeplatz",value:2451},
{hs:"Mannheim, Pestalozzischule",value:2452},
{hs:"Mannheim, Planetarium",value:2453},
{hs:"K&auml;fertal, B&auml;ckerweg",value:2454},
{hs:"Mannheim, Reichsk.-M&uuml;ller-Str.",value:2455},
{hs:"K&auml;fertal, St. Hildegard",value:2456},
{hs:"K&auml;fertal, Joseph-Bauer-Haus",value:2457},
{hs:"Mannheim, Rheinstra&szlig;e",value:2458},
{hs:"Mannheim, Rosengarten",value:2459},
{hs:"Mannheim, Sandgewann",value:2460},
{hs:"K&auml;fertal, V&ouml;lklinger Stra&szlig;e",value:2461},
{hs:"Mannheim, Schloss",value:2462},
{hs:"K&auml;fertal, Therese-Blase-Stra&szlig;e",value:2463},
{hs:"Mannheim, Pfeiffersw&ouml;rth",value:2464},
{hs:"Mannheim, Strohmarkt",value:2465},
{hs:"Mannheim, Tattersall",value:2466},
{hs:"Mannheim, Teufelsbr&uuml;cke",value:2467},
{hs:"K&auml;fertal, Ida-Dehmel-Ring",value:2468},
{hs:"Mannheim, T&Uuml;V",value:2469},
{hs:"Mannheim, Ulmenweg",value:2470},
{hs:"Mannheim, Universit&auml;t",value:2471},
{hs:"Mannheim, Unterm&uuml;hlaustra&szlig;e",value:2472},
{hs:"Mannheim, Verl.Jungbuschstra&szlig;e",value:2473},
{hs:"K&auml;fertal, Wasserwerkstra&szlig;e",value:2474},
{hs:"Mannheim, Wasserturm",value:2475},
{hs:"Mannheim, Weberstra&szlig;e",value:2476},
{hs:"Mannheim, Werderstra&szlig;e",value:2477},
{hs:"Mannheim, Wupperstra&szlig;e",value:2478},
{hs:"Neckarau, Altriper Stra&szlig;e",value:2479},
{hs:"Neckarau, August-Bebel-Stra&szlig;e",value:2480},
{hs:"Neckarau, Bahnhof",value:2481},
{hs:"K&auml;fertal, Ladenburger Stra&szlig;e",value:2482},
{hs:"Neckarau, Dannstadter Stra&szlig;e",value:2483},
{hs:"Sandhofen, Ausgasse",value:2484},
{hs:"Sandhofen, Rathaus",value:2485},
{hs:"Neckarau, Friedhof",value:2486},
{hs:"Neckarau, Friedrichstra&szlig;e",value:2487},
{hs:"Neckarau, Freiheitsplatz",value:2488},
{hs:"Neckarau, Helmertstra&szlig;e",value:2489},
{hs:"Neckarau, Im Morchhof",value:2491},
{hs:"Neckarau, Isarweg",value:2492},
{hs:"Neckarau, Kabel und Draht",value:2493},
{hs:"Neckarau, Lettestra&szlig;e",value:2494},
{hs:"Neckarau, Mallaustra&szlig;e",value:2495},
{hs:"Neckarau, Marktplatz",value:2496},
{hs:"Neckarau, Markuskirche",value:2497},
{hs:"Neckarau, Matth&auml;uskirche",value:2498},
{hs:"Mannheim, Hochschule",value:2499},
{hs:"Lindenhof, Windeckstra&szlig;e",value:2500},
{hs:"Neckarau, Rheingoldhalle",value:2501},
{hs:"Neckarau, Franzosenweg",value:2502},
{hs:"Friedrichsfeld, Holzweg",value:2503},
{hs:"Neckarau, Strandbad",value:2504},
{hs:"Lindenhof, Diesterwegschule",value:2505},
{hs:"Neckarau, Voltastra&szlig;e",value:2506},
{hs:"Neckarau, West",value:2507},
{hs:"Neuhermsheim, Lochg&auml;rten",value:2511},
{hs:"Neuhermsheim, Teufelsloch",value:2513},
{hs:"Neuostheim, Am Sch&auml;ferstock",value:2514},
{hs:"Neuostheim, Harrlach",value:2515},
{hs:"Mannheim, Kopernikusstra&szlig;e",value:2516},
{hs:"Neuostheim, Gr&uuml;newaldstra&szlig;e",value:2517},
{hs:"Neuostheim, Hans-Thoma-Stra&szlig;e",value:2518},
{hs:"Neuostheim, Lucas-Cranach-Str.",value:2519},
{hs:"Neuostheim, Maimarkt",value:2520},
{hs:"Neuostheim, Duale Hochschule",value:2521},
{hs:"Neuostheim, Endstelle",value:2522},
{hs:"Mannheim, Carl-Benz-Stadion",value:2523},
{hs:"Neuostheim, Schwindstra&szlig;e",value:2524},
{hs:"MA-Rheinau, Bahnhof",value:2525},
{hs:"Rheinau, Chiemseestra&szlig;e",value:2526},
{hs:"Rheinau, Faltkistenwerk",value:2527},
{hs:"Rheinau, Fridtjof-Nansen-Weg",value:2528},
{hs:"Rheinau, Frobeniusstra&szlig;e",value:2529},
{hs:"Rheinau, Hallenweg",value:2530},
{hs:"Rheinau, Essener Stra&szlig;e",value:2531},
{hs:"Rheinau, M&uuml;lheimer Stra&szlig;e",value:2532},
{hs:"Neuostheim, Holbeinstra&szlig;e",value:2533},
{hs:"Rheinau, Karl-Schwaner-Stra&szlig;e",value:2534},
{hs:"Rheinau, Leutweinstra&szlig;e",value:2535},
{hs:"Rheinau, Lever",value:2536},
{hs:"Rheinau, L&uuml;deritzstra&szlig;e",value:2537},
{hs:"Rheinau, B36 Abzw. Hirschacker",value:2538},
{hs:"Rheinau, Martinistra&szlig;e",value:2539},
{hs:"Rheinau, Martinskirche",value:2540},
{hs:"Rheinau, M&uuml;nchw&auml;lderstra&szlig;e",value:2542},
{hs:"Rheinau, Neuhofer Stra&szlig;e",value:2543},
{hs:"Rheinau, Karlsplatz",value:2544},
{hs:"Rheinau, Pfingstberg",value:2545},
{hs:"Rheinau, Hafen",value:2546},
{hs:"Rheinau, Rohrhofer Stra&szlig;e",value:2547},
{hs:"Rheinau, Rotterdamer Str. S&uuml;d",value:2548},
{hs:"Rheinau, Ruhrorter Stra&szlig;e",value:2549},
{hs:"Rheinau, Sandrain",value:2550},
{hs:"Rheinau, Pigagestra&szlig;e",value:2551},
{hs:"Rheinau, S&uuml;d",value:2552},
{hs:"Rheinau, Waldseestra&szlig;e",value:2553},
{hs:"Rheinau, Z&uuml;ndholzfabrik",value:2554},
{hs:"Sandhofen, Bartholom&auml;uskirche",value:2555},
{hs:"Sandhofen, Blumenauer Weg",value:2556},
{hs:"Sandhofen, B&uuml;rstadter Stra&szlig;e",value:2557},
{hs:"Sandhofen, Friedhof",value:2558},
{hs:"Sandhofen, F&uuml;llenweg",value:2559},
{hs:"Sandhofen, Hanfstra&szlig;e",value:2560},
{hs:"Sandhofen, K.-Schweizer-Park",value:2561},
{hs:"Sandhofen, Kirschgartshausen",value:2562},
{hs:"Sandhofen, Kr&auml;henfl&uuml;gel",value:2563},
{hs:"Mannheim, Krappm&uuml;hlstra&szlig;e",value:2564},
{hs:"Sandhofen, Sandhofer Weg",value:2565},
{hs:"Sandhofen, Scharhof",value:2566},
{hs:"Sandhofen, Endstelle",value:2567},
{hs:"Mannheim, Collini-Center",value:2569},
{hs:"Blumenau, Blumenau",value:2570},
{hs:"Sch&ouml;nau, Rastenburger Stra&szlig;e",value:2571},
{hs:"Blumenau, Brockenweg",value:2572},
{hs:"Sch&ouml;nau, Graudenzer Linie",value:2573},
{hs:"Sch&ouml;nau, Haderslebener Stra&szlig;e",value:2574},
{hs:"Sch&ouml;nau, Kerschensteinerschule",value:2576},
{hs:"Sch&ouml;nau, K&ouml;nigsberger Allee",value:2577},
{hs:"Vogelstang, Eislebener Weg",value:2578},
{hs:"Vogelstang, Sachsenstra&szlig;e",value:2579},
{hs:"Sch&ouml;nau, Tilsiter Stra&szlig;e",value:2580},
{hs:"Sch&ouml;nau, Max-Winterhalter-Ring",value:2581},
{hs:"Sch&ouml;nau, Memeler Stra&szlig;e",value:2582},
{hs:"Vogelstang, Freiberger Ring",value:2583},
{hs:"Sch&ouml;nau, Sch&ouml;nauschule",value:2584},
{hs:"MA-Seckenheim, Bahnhof",value:2586},
{hs:"Seckenheim, Deutscher Hof",value:2587},
{hs:"Seckenheim, Hochst&auml;tt",value:2588},
{hs:"Seckenheim, Kapellenplatz",value:2589},
{hs:"Seckenheim, L&auml;mmertr&auml;nke",value:2590},
{hs:"Seckenheim, OEG-Bahnhof",value:2591},
{hs:"Seckenheim, Z&auml;hringer Stra&szlig;e",value:2592},
{hs:"Seckenheim, Pforzheimer Stra&szlig;e",value:2593},
{hs:"Seckenheim, Rathaus",value:2594},
{hs:"Seckenheim, Schlittweg",value:2595},
{hs:"Seckenheim, Schwabenstra&szlig;e",value:2596},
{hs:"Seckenheim, Suebenheim",value:2597},
{hs:"Seckenheim, Pumpwerk",value:2599},
{hs:"Vogelstang, Chemnitzer Stra&szlig;e",value:2600},
{hs:"Vogelstang, Im Wohlb&uuml;hl",value:2601},
{hs:"Vogelstang, Magdeburger Stra&szlig;e",value:2602},
{hs:"Vogelstang, Potsdamer Weg",value:2603},
{hs:"Vogelstang, Schweriner Weg",value:2604},
{hs:"Vogelstang, Stra&szlig;enheimer Weg",value:2605},
{hs:"Vogelstang, Endstelle",value:2606},
{hs:"Vogelstang, Warnem&uuml;nder Weg",value:2607},
{hs:"Vogelstang, real",value:2608},
{hs:"Vogelstang, West",value:2609},
{hs:"Vogelstang, Zentrum",value:2610},
{hs:"Waldhof, Alsenweg",value:2611},
{hs:"Waldhof, Altrheinstra&szlig;e",value:2612},
{hs:"Waldhof, Am Herrschaftswald",value:2613},
{hs:"Waldhof, Anemonenweg",value:2614},
{hs:"Waldhof, Bahnhof",value:2615},
{hs:"Waldhof, Roche",value:2616},
{hs:"Waldhof, Eschenhof",value:2617},
{hs:"Waldhof, F&ouml;hrenweg",value:2618},
{hs:"Waldhof, Wetzlarer Winkel",value:2619},
{hs:"Waldhof, Freilichtb&uuml;hne",value:2620},
{hs:"Waldhof, Freyaplatz",value:2621},
{hs:"Waldhof, Gl&uuml;cksburger Weg",value:2622},
{hs:"Waldhof, Kasseler Stra&szlig;e",value:2623},
{hs:"Waldhof, Langer Schlag",value:2624},
{hs:"Waldhof, Neueichwaldstra&szlig;e",value:2625},
{hs:"Waldhof, Nord",value:2626},
{hs:"Waldhof, Papyrus",value:2627},
{hs:"Waldhof, Waldpforte",value:2629},
{hs:"Waldhof, Waldstra&szlig;e",value:2630},
{hs:"Waldhof, Zellstoff-Fabrik",value:2631},
{hs:"Wallstadt, Alemannenstra&szlig;e",value:2632},
{hs:"Wallstadt, Amorbacher Stra&szlig;e",value:2633},
{hs:"Wallstadt, Kies&auml;cker",value:2634},
{hs:"Wallstadt, Bahnhof",value:2635},
{hs:"Wallstadt, Osterburker Stra&szlig;e",value:2636},
{hs:"Wallstadt, Wallstadtschule",value:2638},
{hs:"Wallstadt, Sportanlagen",value:2639},
{hs:"Wallstadt, Wasserturm",value:2640},
{hs:"Mannheim, Arena/Maimarkt (DB)",value:2641},
{hs:"Mannheim, Hansastra&szlig;e",value:2642},
{hs:"Wallstadt, Ost",value:2643},
{hs:"Vogelstang, Spreewaldallee",value:2644},
{hs:"Wallstadt, West",value:2645},
{hs:"Neckarau, Stollenw&ouml;rth",value:2646},
{hs:"Rheinau, Luftschiff",value:2648},
{hs:"Fries. Insel, &Ouml;llager",value:2649},
{hs:"Waldhof, Waldfriedhof Gartens.",value:2650},
{hs:"K&auml;fertal, Malzstra&szlig;e",value:2651},
{hs:"Rheinau, Waldseestra&szlig;e-West",value:2652},
{hs:"Seckenheim, Rastatter Stra&szlig;e",value:2654},
{hs:"Vogelstang, F&uuml;rstenwalder Weg",value:2659},
{hs:"Wallstadt, Auf den Ried",value:2667},
{hs:"Gartenstadt, Otto-Thiele-Platz",value:2670},
{hs:"Wallstadt, Frankenstra&szlig;e",value:2675},
{hs:"Wallstadt, Gotenstra&szlig;e",value:2680},
{hs:"Wallstadt, Friedhof",value:2691},
{hs:"Wallstadt, Storchenstra&szlig;e",value:2693},
{hs:"Wallstadt, Mitte",value:2694},
{hs:"Melm, Georg-Heieck-Stra&szlig;e",value:2696},
{hs:"Fries. Insel, W.-Heisenberg-S.",value:2699},
{hs:"Melm, Robert-Lauth-Stra&szlig;e",value:2734},
{hs:"Sandhofen, IKEA/Scharhof",value:2807},
{hs:"Mannheim, Landzungenstra&szlig;e",value:2809},
{hs:"Maxdorf, Bahnhof",value:2810},
{hs:"Maxdorf, Heideweg",value:2811},
{hs:"Maxdorf, Rathaus",value:2812},
{hs:"Maxdorf, S&uuml;d",value:2814},
{hs:"Maxdorf, Wormser Stra&szlig;e",value:2815},
{hs:"Maxdorf, Zweibr&uuml;cker Stra&szlig;e",value:2816},
{hs:"Maxdorf, Schulzentrum",value:2817},
{hs:"Maxdorf, Hauptstra&szlig;e",value:2819},
{hs:"Meckenheim, B&ouml;hler Stra&szlig;e",value:2820},
{hs:"Meckenheim, Kindergarten",value:2821},
{hs:"Meckenheim, Ost",value:2822},
{hs:"Meckenheim, R&ouml;dersheimer Str.",value:2823},
{hs:"Meckenheim, Sportplatz",value:2824},
{hs:"Meckenheim, West",value:2827},
{hs:"Meckesheim, Bahnhof",value:2835},
{hs:"Mertesheim, Bahnhof",value:2845},
{hs:"Neuhermsheim, SAP Arena",value:2847},
{hs:"Melm, Heinrich-Halfen-Stra&szlig;e",value:2849},
{hs:"Mettenheim, Bahnhof",value:2850},
{hs:"Ludwigshafen, B&ouml;cklinstra&szlig;e",value:2858},
{hs:"Ludwigshafen, Parkinsel",value:2859},
{hs:"Ludwigshafen,Schwanthalerplatz",value:2865},
{hs:"Rheing&ouml;nheim, Gemeindehaus",value:2867},
{hs:"Maudach, S&uuml;d",value:2868},
{hs:"Rheing&ouml;nheim, Hoher Weg",value:2869},
{hs:"Rheing&ouml;nheim, Neuh&ouml;fer Stra&szlig;e",value:2871},
{hs:"Mutterstadt, Schulzentrum",value:2934},
{hs:"Mutterstadt, Blockfeld Nord",value:2935},
{hs:"Mutterstadt, Blockfeld S&uuml;d",value:2936},
{hs:"Mutterstadt, Buchenstra&szlig;e",value:2937},
{hs:"Mutterstadt, Dahlienstra&szlig;e",value:2938},
{hs:"Mutterstadt, Friedhof",value:2939},
{hs:"Mutterstadt, West (Heinestr.)",value:2940},
{hs:"Mutterstadt, Kreisbad",value:2941},
{hs:"Mutterstadt, Neue Pforte",value:2942},
{hs:"Mutterstadt, Pfalzring",value:2943},
{hs:"Mutterstadt, R&ouml;ntgenstra&szlig;e",value:2944},
{hs:"Mutterstadt, Schifferstadt Str",value:2945},
{hs:"Mutterstadt, Speyerer Stra&szlig;e",value:2946},
{hs:"Mutterstadt, S&uuml;d",value:2947},
{hs:"Mutterstadt, Waldstra&szlig;e",value:2948},
{hs:"Mutterstadt, West",value:2949},
{hs:"Mutterstadt, Brunnenstra&szlig;e",value:2950},
{hs:"Mutterstadt, B&uuml;rgermeisteramt",value:2952},
{hs:"Mutterstadt, Nord",value:2953},
{hs:"Mutterstadt, Thomas-Mann-Str.",value:2955},
{hs:"Neckargem&uuml;nd, Bahnhof",value:2986},
{hs:"Neckargem&uuml;nd, Altstadt",value:2994},
{hs:"Ludwigshafen, Apostelkirche",value:3012},
{hs:"Neuhermsheim, Husarenweg",value:3024},
{hs:"Neuhermsheim, Ulanenweg",value:3025},
{hs:"Neuhermsheim, Gerd-Dehof-Platz",value:3026},
{hs:"Neuhermsheim, SAP Arena S&uuml;d",value:3027},
{hs:"Mannheim, Technoseum S&uuml;d",value:3028},
{hs:"Neckarhausen b.Neckarsteinach",value:3045},
{hs:"Neckarsteinach, Bahnhof",value:3047},
{hs:"Neidenfels, Bahnhof",value:3062},
{hs:"Ladenburg, Daimlerstra&szlig;e",value:3073},
{hs:"Ladenburg, Martinsg&auml;rten",value:3074},
{hs:"Neuhofen, Carl-Rei&szlig;-Stra&szlig;e",value:3075},
{hs:"Neuhofen, Rathaus",value:3076},
{hs:"Neuhofen, Kupfernagel",value:3077},
{hs:"Neuhofen, Rehbachstra&szlig;e",value:3078},
{hs:"Neuhofen, Speyerer Stra&szlig;e",value:3079},
{hs:"Neuhofen, Stechgraben",value:3080},
{hs:"Neuhofen, Unterwald",value:3081},
{hs:"Neuhofen, Partnerschaftsplatz",value:3082},
{hs:"Neuhofen, Woogstra&szlig;e",value:3083},
{hs:"Neulu&szlig;heim, Apotheke",value:3100},
{hs:"Neulu&szlig;heim, Bahnhof",value:3101},
{hs:"Neulu&szlig;heim, Rathaus",value:3102},
{hs:"Duttweiler, Abzw.",value:3105},
{hs:"Geinsheim, Kirche",value:3111},
{hs:"Geinsheim, Kreuz",value:3112},
{hs:"Ladenburg, Alte Martinsschule",value:3117},
{hs:"Lachen, Flugplatz",value:3129},
{hs:"Lachen, Kirrweiler Stra&szlig;e",value:3130},
{hs:"Lachen, Linde",value:3131},
{hs:"Lachen, Pf&auml;lzer Hof",value:3132},
{hs:"Lachen, Schloss",value:3133},
{hs:"Neustadt, Hauptbahnhof",value:3144},
{hs:"Neustadt, B&ouml;big",value:3145},
{hs:"Speyerdorf, Hammann",value:3184},
{hs:"Speyerdorf, Pfirmann",value:3186},
{hs:"Speyerdorf, W&auml;scherei",value:3188},
{hs:"Niederkirchen, Denkmal",value:3240},
{hs:"Niederkirchen, Kirche",value:3241},
{hs:"Niederkirchen, Winzer",value:3242},
{hs:"Obers&uuml;lzen, Abzw. Obrigheim",value:3260},
{hs:"Obers&uuml;lzen, Laumersheimer Str.",value:3261},
{hs:"Obers&uuml;lzen, Post",value:3262},
{hs:"Luzenberg, Ost",value:3278},
{hs:"Ludwigshafen, Nachtweide",value:3284},
{hs:"Oftersheim, Bahnhof",value:3285},
{hs:"Oftersheim, Hardtwaldring",value:3286},
{hs:"Oftersheim, Hockenheimer Str.",value:3287},
{hs:"Oftersheim, Rathaus",value:3288},
{hs:"Oftersheim, Am Alten Schiesst.",value:3289},
{hs:"Oftersheim, Wiesenstra&szlig;e",value:3290},
{hs:"Oftersheim, Lessingstra&szlig;e",value:3292},
{hs:"Osthofen, Bahnhof",value:3295},
{hs:"Neckarau, Flo&szlig;w&ouml;rth",value:3306},
{hs:"Otterstadt, Kreuz",value:3310},
{hs:"Otterstadt, Mannheimer Stra&szlig;e",value:3311},
{hs:"Otterstadt, Mitte",value:3312},
{hs:"Plankstadt, Altenheim",value:3315},
{hs:"Plankstadt, Eisenbahnstra&szlig;e",value:3316},
{hs:"Plankstadt, Rathaus",value:3317},
{hs:"Bo&szlig;weilerhof",value:3320},
{hs:"Quirnheim, Tal",value:3321},
{hs:"Quirnheim, Ort",value:3322},
{hs:"Reilingen, Hauptstra&szlig;e",value:3340},
{hs:"Reilingen, Haydnallee",value:3341},
{hs:"Reilingen, Kath. Kindergarten",value:3342},
{hs:"Reilingen, Wilhelmstra&szlig;e",value:3344},
{hs:"Reilingen, Rathaus",value:3345},
{hs:"Reilingen, Sportplatz",value:3346},
{hs:"Reilingen, Trafostation",value:3347},
{hs:"Walldorf, Nahversorgungszentr.",value:3377},
{hs:"Gronau, Mitte",value:3381},
{hs:"Gronau, Ost",value:3382},
{hs:"Mechtersheim, Trifelsstra&szlig;e",value:3384},
{hs:"Berghausen, Kirche",value:3385},
{hs:"Heiligenstein, Dorfbrunnen",value:3388},
{hs:"Mechtersheim, Speyerer Stra&szlig;e",value:3389},
{hs:"Berghausen, Abzw. Bahnhof",value:3390},
{hs:"Berghausen (Pfalz) Bahnhof",value:3391},
{hs:"Berghausen, Marxenweidenweg",value:3392},
{hs:"Heiligenstein, Bahnhof",value:3393},
{hs:"Heiligenstein, Hallenbad",value:3395},
{hs:"Heiligenstein, Kreuz",value:3396},
{hs:"Mechtersheim, Kirche",value:3397},
{hs:"Heiligenstein, Viehtrifftstr.",value:3400},
{hs:"Berghausen, B&uuml;rgermeisteramt",value:3404},
{hs:"Ruppertsberg, Hohe Burg",value:3405},
{hs:"Ruppertsberg, Pf&auml;lzer Hof",value:3406},
{hs:"Ruppertsberg, Winzer",value:3407},
{hs:"Schifferstadt, Bahnhof",value:3430},
{hs:"Schifferstadt, S&uuml;dbahnhof",value:3434},
{hs:"Schifferstadt, Salierschule",value:3437},
{hs:"Schifferstadt, Schulzentrum",value:3438},
{hs:"Schriesheim, Fensenb&auml;umen",value:3469},
{hs:"Altenbach, Ost",value:3471},
{hs:"Altenbach, Rathaus",value:3472},
{hs:"Altenbach, R&ouml;schbach",value:3473},
{hs:"Altenbach, Siedlung",value:3474},
{hs:"Schriesheim, Edelstein",value:3475},
{hs:"Schriesheim, Ladenburger Str.",value:3476},
{hs:"Schriesheim, Ludwigstal",value:3477},
{hs:"Schriesheim, Rathaus",value:3478},
{hs:"Schriesheim, Bahnhof",value:3479},
{hs:"Schriesheim, Schwimmbad",value:3480},
{hs:"Schriesheim, Stammberg",value:3481},
{hs:"Schriesheim, S&uuml;d",value:3482},
{hs:"Schriesheim, Weites Tal",value:3483},
{hs:"Schriesheim, Zentgrafenstra&szlig;e",value:3484},
{hs:"Ursenbach, Estenklinge",value:3485},
{hs:"Ursenbach, Ort",value:3486},
{hs:"Ursenbach, Ursenbacher Hof",value:3487},
{hs:"Schwetzingen, S&uuml;dtangente",value:3498},
{hs:"Schwetzingen, Schloss",value:3499},
{hs:"Hirschacker, Biologische Insel",value:3500},
{hs:"Hirschacker, Kaserne",value:3501},
{hs:"Hirschacker, Marktplatz",value:3502},
{hs:"Hirschacker, Siedlerstra&szlig;e",value:3503},
{hs:"Schwetzingen, Aug.-Neuhaus-Str",value:3504},
{hs:"Schwetzingen, Bahnhof",value:3505},
{hs:"Schwetzingen, Bismarckstra&szlig;e",value:3506},
{hs:"Schwetzingen, Evang. Kirche",value:3507},
{hs:"Schwetzingen, Krankenhaus",value:3508},
{hs:"Schwetzingen, Friedhof",value:3509},
{hs:"Schwetzingen, Fr.-Ebert-Str.",value:3510},
{hs:"Schwetzingen, Herzogstra&szlig;e",value:3511},
{hs:"Schwetzingen, Krankenhaus B 36",value:3512},
{hs:"Schwetzingen, Langer Sand",value:3513},
{hs:"Schwetzingen, Markgrafenstra&szlig;e",value:3514},
{hs:"Schwetzingen, Rabaliatti Str.",value:3515},
{hs:"Schwetzingen, K&ouml;nigs&auml;cker",value:3516},
{hs:"Schwetzingen, Schlossplatz",value:3517},
{hs:"Schwetzingen, C.-Theodor-Br&uuml;ck",value:3518},
{hs:"Schwetzingen, Stadion",value:3519},
{hs:"Schwetzingen, Stamitzstra&szlig;e",value:3520},
{hs:"Schwetzingen, Storchen",value:3521},
{hs:"Schwetzingen, Berliner Stra&szlig;e",value:3522},
{hs:"Schwetzingen, Grenzh&ouml;fer Str.",value:3523},
{hs:"Schwetzingen, Holzbauerstra&szlig;e",value:3524},
{hs:"Schwetzingen, Verschaffeltstr.",value:3525},
{hs:"Schwetzingen, Kronenstra&szlig;e",value:3526},
{hs:"Schwetzingen, Sch&auml;lzigweg",value:3527},
{hs:"Schwetzingen, Sauerbruchstra&szlig;e",value:3528},
{hs:"Schwetzingen, Helmholtzstra&szlig;e",value:3529},
{hs:"Schwetzingen, Rich.-Wagner-Str",value:3530},
{hs:"Schwetzingen, Kurpfalzring",value:3531},
{hs:"Schwetzingen, Lessingstra&szlig;e",value:3532},
{hs:"Schwetzingen, Scheffelstra&szlig;e",value:3533},
{hs:"Schwetzingen, Bellamar",value:3534},
{hs:"Sinsheim, Hauptbahnhof",value:3550},
{hs:"Steinsfurt, Bahnhof",value:3561},
{hs:"Speyer, Postgraben",value:3594},
{hs:"Speyer, Hbf/ZOB",value:3603},
{hs:"Speyer, Martin-Greif-Str./&Auml;rzt",value:3614},
{hs:"Speyer, Domplatz",value:3618},
{hs:"Speyer-Nord, Erlenweg",value:3620},
{hs:"Speyer-Nord, Ruhhecke",value:3624},
{hs:"Speyer, Karl-Leiling-Allee",value:3626},
{hs:"Speyer, Friedhof",value:3627},
{hs:"Speyer, Ged&auml;chtniskirche",value:3630},
{hs:"Speyer, Geisselstra&szlig;e",value:3632},
{hs:"Speyer, Hirschgraben",value:3637},
{hs:"Speyer-Nord, Kaserne",value:3644},
{hs:"Speyer, Nord/West",value:3650},
{hs:"Speyer-Nord, Nu&szlig;baumweg",value:3668},
{hs:"Speyer-Nord, Otterstadter Weg",value:3672},
{hs:"Speyer, Postplatz",value:3673},
{hs:"Speyer, Stadthalle",value:3686},
{hs:"Speyer, Bartholom&auml;us-Weltz-Pl.",value:3695},
{hs:"Speyer, Bahnhofsvorplatz",value:3696},
{hs:"Speyer, Doppel-Gymnasium",value:3704},
{hs:"Germersheim, S&uuml;d/Nolte",value:3712},
{hs:"Graben-Neudorf, Nord",value:3729},
{hs:"Eisenberg (Pfalz), Bahnhof",value:3798},
{hs:"R&uuml;ssingen, Ort",value:3801},
{hs:"Bubenheim, Ort",value:3802},
{hs:"Rot-Malsch, Bahnhof",value:3806},
{hs:"Viernheim, Am Frohnberg",value:3821},
{hs:"Viernheim, Sandstra&szlig;e",value:3828},
{hs:"Viernheim, Pirmasenser Stra&szlig;e",value:3829},
{hs:"Viernheim, Altenwohnheim",value:3831},
{hs:"Viernheim, Am Schmittsberg",value:3832},
{hs:"Viernheim, Sepp-Herberger-Weg",value:3833},
{hs:"Viernheim, B&uuml;rgerhaus",value:3834},
{hs:"Viernheim, Eissporthalle",value:3835},
{hs:"Viernheim, Erzbergerstra&szlig;e",value:3836},
{hs:"Viernheim, Friedhof",value:3837},
{hs:"Viernheim, Hallenbad",value:3838},
{hs:"Viernheim, H&uuml;gelstra&szlig;e",value:3839},
{hs:"Viernheim, Jahnstra&szlig;e",value:3840},
{hs:"Viernheim, Kapellenberg",value:3841},
{hs:"Viernheim, Erich-K&auml;stner-Allee",value:3842},
{hs:"Viernheim, Kirschenstr./Kind.",value:3843},
{hs:"Viernheim, Kon.-Adenauer-Allee",value:3844},
{hs:"Viernheim, Lilienthalstra&szlig;e",value:3845},
{hs:"Viernheim, Melibokusstra&szlig;e",value:3846},
{hs:"Viernheim, Moselstra&szlig;e",value:3847},
{hs:"Viernheim, K&auml;the-Kollwitz-Str.",value:3848},
{hs:"Viernheim, Neust&auml;dter Stra&szlig;e",value:3849},
{hs:"Viernheim, W. Oehmichen-Stra&szlig;e",value:3850},
{hs:"Viernheim, Bahnhof",value:3851},
{hs:"Viernheim, W.-Gropius-Allee",value:3852},
{hs:"Viernheim, Ost",value:3853},
{hs:"Viernheim, Pestalozzistra&szlig;e",value:3854},
{hs:"Viernheim, Potters-Bar-Platz",value:3855},
{hs:"Viernheim, Rathausstra&szlig;e",value:3856},
{hs:"Viernheim, R&ouml;ntgenstra&szlig;e",value:3858},
{hs:"Ludwigshafen, Bismarckstra&szlig;e",value:3859},
{hs:"Viernheim, Levi-Strauss-Allee",value:3860},
{hs:"Viernheim, Schulzentrum",value:3861},
{hs:"Viernheim, Alfred-Nobel-Stra&szlig;e",value:3862},
{hs:"Viernheim, Spitalplatz",value:3863},
{hs:"Viernheim, Stadtwerke",value:3864},
{hs:"Viernheim, Tivoli (RNZ)",value:3865},
{hs:"Viernheim, Eichendorffstra&szlig;e",value:3866},
{hs:"Viernheim, Waldschwimmbad",value:3867},
{hs:"Viernheim, Werkstra&szlig;e",value:3869},
{hs:"Viernheim, Wernherstra&szlig;e",value:3870},
{hs:"Viernheim, Aussiedlerhof Blae&szlig;",value:3872},
{hs:"Viernheim, Baumann",value:3873},
{hs:"Viernheim, Wallachei",value:3874},
{hs:"Viernheim, Hoock",value:3875},
{hs:"Viernheim, Haas",value:3876},
{hs:"Viernheim, Kettelerstra&szlig;e",value:3877},
{hs:"Viernheim, H.-von-Brentano-Al",value:3878},
{hs:"Viernheim, T.I.B.",value:3881},
{hs:"Viernheim, Neuh&auml;userstra&szlig;e",value:3887},
{hs:"Viernheim, Waldfriedhof",value:3892},
{hs:"Neuhermsheim, SAP Arena S-Bf.",value:3894},
{hs:"Wachenheim/Wstr, Bahnhof",value:3895},
{hs:"Wachenheim/Wstr, J&auml;gertal",value:3897},
{hs:"Wachenheim/Wstr, Oberstnest",value:3899},
{hs:"Wagh&auml;usel, Bahnhof",value:3916},
{hs:"Wiesental, Bahnhof",value:3919},
{hs:"Waldsee, Partnerschaftsplatz",value:4008},
{hs:"Waldsee, Friedhof",value:4010},
{hs:"Waldsee, Schwanenplatz",value:4013},
{hs:"Waldsee, Rathaus",value:4015},
{hs:"Waldsee, Oberlache",value:4016},
{hs:"Walldorf, Drehscheibe",value:4025},
{hs:"Walldorf, Rennbahnstra&szlig;e",value:4037},
{hs:"Wattenheim/Pf, Hetschm&uuml;hle",value:4060},
{hs:"Wattenheim/Pf, Unterdorf",value:4061},
{hs:"Wattenheim/Pf, Oberdorf",value:4062},
{hs:"Weidenthal, Bahnhof",value:4065},
{hs:"Hohensachsen",value:4077},
{hs:"L&uuml;tzelsachsen, Bahnhof",value:4081},
{hs:"L&uuml;tzelsachsen, OEG-Bahnhof",value:4084},
{hs:"L&uuml;tzelsachsen, Pilgerhaus",value:4085},
{hs:"Weinheim, Blumenstra&szlig;e",value:4105},
{hs:"Weinheim, Bahnhof",value:4109},
{hs:"Weinheim, Freiburger Stra&szlig;e",value:4113},
{hs:"Weinheim, H&auml;ndelstra&szlig;e",value:4118},
{hs:"Weinheim, Luisenstr. (zur DB)",value:4126},
{hs:"Weinheim, Rosenbrunnen",value:4132},
{hs:"Weinheim, Stahlbad",value:4136},
{hs:"Weinheim, OEG-Bahnhof",value:4146},
{hs:"Weisenheim/S, Bahnhof",value:4205},
{hs:"Wiesloch-Walldorf, Bf",value:4252},
{hs:"Wilhelmsfeld, Autohalle",value:4290},
{hs:"Wilhelmsfeld, Kipp",value:4292},
{hs:"Wilhelmsfeld, Rathaus",value:4293},
{hs:"Wilhelmsfeld, Schriesheim. Hof",value:4295},
{hs:"Wilhelmsfeld, Wilhelmsh&ouml;he",value:4297},
{hs:"Horchheim, Benzstra&szlig;e",value:4331},
{hs:"Weinsheim, Zollhaus",value:4394},
{hs:"Worms, Hauptbahnhof",value:4415},
{hs:"Zwingenberg, Bahnhof",value:4526},
{hs:"Ottersheim/Pfrimm, Kirche",value:4577},
{hs:"Rheing&ouml;nheim, Hauptstra&szlig;e",value:4606},
{hs:"Lingenfeld, Siedlung",value:4635},
{hs:"Schwetzingen, Mannh. Landstr.",value:4701},
{hs:"Schwetzingen, Marstallstra&szlig;e",value:4702},
{hs:"Biedesheim, Ort/Turm",value:4728},
{hs:"Oppau, Friedhof",value:4743},
{hs:"Gauersheim, Ort",value:4818},
{hs:"Rittersheim, Ort",value:4819},
{hs:"Bischheim, Kupferm&uuml;hle",value:4820},
{hs:"Bodenheim, Bahnhof",value:4849},
{hs:"Steinborn, Lessingstra&szlig;e",value:4878},
{hs:"Ramsen, Eiswoog",value:4892},
{hs:"Frankenthal, Gegelstra&szlig;e",value:4938},
{hs:"Eisenberg, Abzw. Bahnhof",value:4989},
{hs:"Eisenberg, Abzw. Steinborn",value:4990},
{hs:"Ramsen (Pfalz), Bahnhof",value:5000},
{hs:"R&ouml;dersheim, Hoher Weg",value:5010},
{hs:"Dannstadt, Von-Stein-Stra&szlig;e",value:5011},
{hs:"Dannstadt, Kurpfalzschule",value:5012},
{hs:"Dannstadt, Mutterstadter Str.",value:5013},
{hs:"Dannstadt, Angelstra&szlig;e",value:5014},
{hs:"Schauernheim, Hintergasse",value:5015},
{hs:"Schauernheim, Gartenstra&szlig;e",value:5016},
{hs:"Mutterstadt, Rheing&ouml;nheim. Str",value:5019},
{hs:"Mutterstadt, Luitpoldstra&szlig;e",value:5021},
{hs:"Mutterstadt, Ost",value:5023},
{hs:"Viernheim, Schriesheimer Str.",value:5055},
{hs:"Viernheim, Neuzenlache",value:5056},
{hs:"Viernheim, Ziegelh&uuml;tte",value:5057},
{hs:"Frankenthal, Nachtweideweg",value:5088},
{hs:"Ruchheim, Paul-M&uuml;nch-Stra&szlig;e",value:5152},
{hs:"Speyer, Landauer Stra&szlig;e",value:5235},
{hs:"Albisheim, Hauptstra&szlig;e",value:5270},
{hs:"Kirchheimbolanden, Kreisverw.",value:5286},
{hs:"G&ouml;llheim, Wormser Stra&szlig;e",value:5472},
{hs:"Neckarau, Franz-Sigel-Stra&szlig;e",value:5540},
{hs:"Mannheim, Kunsthalle",value:5542},
{hs:"Mannheim, Theresienkrankenhaus",value:5543},
{hs:"Mannheim, Universit&auml;tsklinikum",value:5544},
{hs:"K&auml;fertal, Mannheimer Stra&szlig;e",value:5545},
{hs:"K&auml;fertal, Im Rott",value:5546},
{hs:"K&auml;fertal, Bahnhof (RNV)",value:5547},
{hs:"Mannheim, Alte Feuerwache",value:5548},
{hs:"Mannheim, MVV-Hochhaus",value:5549},
{hs:"Mannheim, Neumarkt",value:5550},
{hs:"Sch&ouml;nau, Endstelle",value:5553},
{hs:"Sch&ouml;nau, Thorner Stra&szlig;e",value:5554},
{hs:"Blumenau, Eugen-Neter-Schule",value:5555},
{hs:"Sch&ouml;nau, Sonderburger Stra&szlig;e",value:5556},
{hs:"Feudenheim, Bl&uuml;cherstra&szlig;e",value:5557},
{hs:"Rheinau, Antwerpener Stra&szlig;e",value:5558},
{hs:"Rheinau, Hofrat-Wild-Stra&szlig;e",value:5559},
{hs:"Lindenhof, Pfalzplatz",value:5560},
{hs:"Fries. Insel, Otto-Hahn-Stra&szlig;e",value:5562},
{hs:"Heddesheim, Bahnhof (RNV)",value:5563},
{hs:"Waldhof, Haus Waldhof",value:5575},
{hs:"Waldhof, Karl-Feuerstein-Str.",value:5588},
{hs:"Waldhof, Wiesbadener Stra&szlig;e",value:5589},
{hs:"Mannheim, Schafweide",value:5590},
{hs:"Waldhof, D&uuml;ppelweg",value:5641},
{hs:"Luzenberg, Hafenbahnstra&szlig;e",value:5647},
{hs:"Rheinau, Dortmunder Stra&szlig;e",value:5698},
{hs:"Br&uuml;hl, Hima",value:5699},
{hs:"Oggersheim, Endstelle",value:5700},
{hs:"Neuhofen, Otto-Ditscher-Haus",value:5701},
{hs:"Limburgerhof, Rudolf-Wihr-Sch.",value:5702},
{hs:"Dossenheim, Nord",value:5742},
{hs:"Br&uuml;hl, Realschule",value:5870},
{hs:"Frankenthal, Fontanesistra&szlig;e",value:5880},
{hs:"Studernheim, Frankenthaler Str",value:5884},
{hs:"Frankenthal, Sparkasse ADR",value:5885},
{hs:"Frankenthal, Pegulan",value:5890},
{hs:"Frankenthal, Mierendorffstra&szlig;e",value:5891},
{hs:"Frankenthal, Finkenweg",value:5892},
{hs:"Frankenthal, Justizvollzugsan.",value:5893},
{hs:"Mannheim, Mensa am Schloss",value:6004},
{hs:"Mannheim, Akademiestra&szlig;e",value:6005},
{hs:"Mannheim, Hafenstra&szlig;e",value:6006},
{hs:"Mannheim, Verbindungskanal",value:6007},
{hs:"Seckenheim, Otto-Bauder-Sport",value:6029},
{hs:"Seckenheim, Kaiserstuhlring",value:6030},
{hs:"Seckenheim, Innerer Heckweg",value:6031},
{hs:"Rheinau, Pfingstberg Sportanl.",value:6036},
{hs:"Mannheim, Rathaus/Reiss-Museum",value:6041},
{hs:"Heddesheim, Reithalle",value:6059},
{hs:"Mannheim, Am Salzkai",value:6080},
{hs:"Leutersh.Gewerbegeb.Hirschberg",value:6084},
{hs:"Birkenheide, Hundertmorgenstr.",value:6132},
{hs:"Pfingstweide, Prager Stra&szlig;e",value:6158},
{hs:"Rheinau, Holl&auml;nderstra&szlig;e",value:6159},
{hs:"K&auml;fertal, Birkenauer Stra&szlig;e",value:6160},
{hs:"Lampertheim, Rathaus",value:6280},
{hs:"Iggelheim, Luitpoldstra&szlig;e",value:6298},
{hs:"Mosbach, Westbahnhof",value:6343},
{hs:"Bruchsal, Gew. Bildungszentrum",value:6344},
{hs:"Frankenthal, G.-Daimler-Stra&szlig;e",value:6358},
{hs:"Heddesheim, Kronenplatz",value:6422},
{hs:"Heddesheim, Post",value:6423},
{hs:"Heddesheim, Wasserbett/Unterd.",value:6424},
{hs:"Heddesheim, Wielandstra&szlig;e",value:6425},
{hs:"Heddesheim, A.-Lortzing-/Muck.",value:6426},
{hs:"Heddesheim, Ring-/Verl.Triebs.",value:6427},
{hs:"Heddesheim, Friedhof",value:6428},
{hs:"Heddesheim, Mannheimer Stra&szlig;e",value:6429},
{hs:"Heddesheim, Beethovenstra&szlig;e",value:6430},
{hs:"Heddesheim, In der Sackpfeife",value:6431},
{hs:"Heddesheim, Linden-/Triebstr.",value:6432},
{hs:"Heddesheim, Bismarck-/Vorstadt",value:6433},
{hs:"Heddesheim, Schlatterstra&szlig;e",value:6434},
{hs:"Heddesheim, Westendstra&szlig;e",value:6435},
{hs:"Muckensturm, Ort",value:6436},
{hs:"Heddesheim, Muckensturmer Str",value:6439},
{hs:"Heddesheim, Hans-Thoma-Schule",value:6440},
{hs:"Leutershausen, Goethe-/Beethov",value:6441},
{hs:"Leutershausen, Weinbergstra&szlig;e",value:6442},
{hs:"Leutershausen, Endweg/Burgweg",value:6443},
{hs:"Leutershausen, Friedhof",value:6444},
{hs:"Leutershausen, Dohlweg/Lindenb",value:6445},
{hs:"Leutershausen, Ob. H&auml;uselberg",value:6446},
{hs:"Leutershausen, Unt. H&auml;uselberg",value:6447},
{hs:"Leutershausen, Brombeerweg",value:6448},
{hs:"Leutershausen, Rathaus",value:6449},
{hs:"Leutershausen, Markthalle",value:6450},
{hs:"Leutershausen, Gartenstra&szlig;e",value:6452},
{hs:"Leutershausen, Breslauer-/Man",value:6453},
{hs:"Leutershausen, Freiburger-/La.",value:6454},
{hs:"Heddesheim, Ladenburger Stra&szlig;e",value:6455},
{hs:"Leutershausen, Sportzentrum",value:6456},
{hs:"Leutershausen, Dr.-W.-Schmitt",value:6457},
{hs:"Leutershausen, Goethe-/H&ouml;lderl",value:6458},
{hs:"Leutershausen , Hans-Thoma-Str",value:6459},
{hs:"Gro&szlig;sachsen, Im Br&uuml;nnel/Winzer",value:6460},
{hs:"Gro&szlig;sachsen, Sachsenhalle",value:6461},
{hs:"Gro&szlig;sachsen, Fr.-Ebert/Lessing",value:6462},
{hs:"Gro&szlig;sachsen, Ahornstra&szlig;e",value:6463},
{hs:"Gro&szlig;sachsen, Marktplatz",value:6464},
{hs:"Gro&szlig;sachsen, Lettengasse/Im Br",value:6465},
{hs:"Gro&szlig;sachsen, Friedhof",value:6466},
{hs:"Gro&szlig;sachsen, Altes Schulhaus",value:6467},
{hs:"Gro&szlig;sachsen, Talstr./Lettengas",value:6468},
{hs:"Gro&szlig;sachsen, Jahnstra&szlig;e",value:6469},
{hs:"Br&uuml;hl, F&auml;hre",value:6480},
{hs:"Br&uuml;hl, Kollerinsel",value:6481},
{hs:"Dannstadt, VG (Rathaus)",value:6525},
{hs:"Dannstadt, VG (Schubertstra&szlig;e)",value:6526},
{hs:"Heddesheim, Seniorenbegegn.",value:6543},
{hs:"Heddesheim, Nordbadenhalle",value:6565},
{hs:"Eppstein, Verdistra&szlig;e",value:6585},
{hs:"Ilvesheim, Neckarhalle",value:6606},
{hs:"Ilvesheim, Friedhof Nord",value:6610},
{hs:"Friesenheim, Ebertpark S&uuml;d",value:6645},
{hs:"Friesenheim, V&ouml;lklinger Stra&szlig;e",value:6646},
{hs:"Friesenheim, Burbacher Stra&szlig;e",value:6647},
{hs:"Oggersheim, Erich-K&auml;stner-Str.",value:6648},
{hs:"Oggersheim, Westlich B9",value:6649},
{hs:"Oggersheim, Oderstra&szlig;e",value:6650},
{hs:"Heddesheim, Werderstra&szlig;e",value:6706},
{hs:"Heddesheim, Leutershausener St",value:6707},
{hs:"Neckarhausen, Friedhof",value:6709},
{hs:"Pfingstweide, Budapester Str.",value:6739},
{hs:"Pfingstweide, Londoner Ring",value:6740},
{hs:"Mannheim, Universit&auml;t West",value:6755},
{hs:"Walldorf, SAP Campus",value:6756},
{hs:"Viernheim, Schneider",value:6763},
{hs:"Mannheim, K&auml;fertaler Stra&szlig;e",value:6764},
{hs:"Deidesheim, Regionale Schule",value:6772},
{hs:"Adelsheim, Nordbahnhof",value:6777},
{hs:"Iggelheim, Eisenbahnstra&szlig;e",value:6793},
{hs:"Heidelberg, Montpellierbr&uuml;cke",value:6794},
{hs:"Ilvesheim, Heddesheimer Stra&szlig;e",value:6802},
{hs:"Maudach, Irisstra&szlig;e",value:6803},
{hs:"Maudach, Nelkestra&szlig;e",value:6804},
{hs:"Maudach, Riedstra&szlig;e",value:6805},
{hs:"Rheing&ouml;nheim, Am Sandloch",value:6806},
{hs:"Oggersheim, Wasserwerk",value:6807},
{hs:"Niederfeld, Karlsbader Stra&szlig;e",value:6808},
{hs:"Niederfeld, Berufsbildungsz.",value:6809},
{hs:"Niederfeld, Heuweg",value:6810},
{hs:"Eppstein, Studernheimer Weg",value:6819},
{hs:"Walldorf, Astoria-Halle",value:6843},
{hs:"Asselheim, Im Battenb&uuml;hl",value:6844},
{hs:"Neuostheim, Eastsite",value:6856},
{hs:"Ludwigshafen, Strandbad Blies",value:6877},
{hs:"Oggersheim, In den Neug&auml;rten",value:6878},
{hs:"Ilvesheim, Schriesheimer Str.",value:6924},
{hs:"Ilvesheim, Mahrgrund",value:6933},
{hs:"Plankstadt, Eppelheimer Stra&szlig;e",value:7123},
{hs:"Oggersheim, Gro&szlig;parthweiher",value:7125},
{hs:"Gro&szlig;sachsen, S&uuml;d",value:7140},
{hs:"Kirchheim, Grasweg",value:7279},
{hs:"Mannheim, Kolpingstra&szlig;e",value:7303},
{hs:"Ludwigshafen, Walzm&uuml;hle",value:7520},
{hs:"Ludwigshafen, Rheinallee S&uuml;d",value:7521},
{hs:"Ludwigshafen, Drehbr&uuml;cke",value:7522},
{hs:"Ludwigshafen, Rheinallee Nord",value:7526},
{hs:"Rheinzabern, Alte R&ouml;merstra&szlig;e",value:7913},
{hs:"Rheinzabern, Rappengasse",value:7914},
{hs:"Bellheim, Am M&uuml;hlbuckel",value:7915},
{hs:"Germersheim, Mitte/Rhein",value:7919},
{hs:"R&uuml;lzheim, Freizeitzentrum",value:7922},
{hs:"Darmstadt, Eberstadt",value:8014},
{hs:"Bickenbach, Bahnhof",value:8015},
{hs:"Darmstadt, S&uuml;d",value:8016},
{hs:"Mainz, R&ouml;misches Theater",value:8018},
{hs:"Nackenheim, Bahnhof",value:8083},
{hs:"Nierstein, Bahnhof",value:8084},
{hs:"Oppenheim, Bahnhof",value:8085},
{hs:"Philippsburg, Bahnhof",value:8100},
{hs:"Rheinsheim, Bahnhof",value:8101},
{hs:"Huttenheim, Bahnhof",value:8102},
{hs:"Karlsdorf, Bahnhof",value:8103},
{hs:"Homburg, Hbf",value:8120},
{hs:"Bruchm&uuml;hlbach-Miesau, Bahnhof",value:8121},
{hs:"Hauptstuhl, Bahnhof",value:8122},
{hs:"Landstuhl, Bahnhof",value:8123},
{hs:"Kindsbach, Bahnhof",value:8124},
{hs:"Einsiedlerhof, Bahnhof",value:8125},
{hs:"Vogelweh",value:8126},
{hs:"Kennelgarten, Bahnhof",value:8127},
{hs:"Laubenheim, Bahnhof",value:8181},
{hs:"Osterburken, Bahnhof",value:8200},
{hs:"Zimmern, Bahnhof",value:8202},
{hs:"Seckach, Bahnhof",value:8203},
{hs:"Eicholzheim, Bahnhof",value:8204},
{hs:"Oberschefflenz, Bahnhof",value:8205},
{hs:"Auerbach/Mb, Bahnhof",value:8206},
{hs:"Dallau, Bahnhof",value:8207},
{hs:"Neckarburken, Bahnhof",value:8208},
{hs:"Mosbach, Bahnhof",value:8209},
{hs:"Heilbronn, Hbf",value:8242},
{hs:"Neckarsulm, Bahnhof",value:8269},
{hs:"Sondernheim, Bahnhof",value:8270},
{hs:"Bellheim, Bahnhof",value:8271},
{hs:"R&uuml;lzheim, Bahnhof",value:8272},
{hs:"Rheinzabern, Bahnhof",value:8273},
{hs:"Jockgrim, Bahnhof",value:8274},
{hs:"W&ouml;rth/Rh, Bahnhof",value:8275},
{hs:"W&ouml;rth, Z&uuml;gelstr.",value:8289},
{hs:"Karlsruhe-Knielingen",value:8310},
{hs:"Karlsruhe, Durlach Bf",value:8315},
{hs:"Karlsruhe, Marktplatz",value:8317},
{hs:"Karlsruhe, Europaplatz",value:8318},
{hs:"Karlsruhe, Entenfang",value:8319},
{hs:"H&auml;hnlein-Alsbach, Bahnhof",value:8394},
{hs:"Bad Wimpfen, Bahnhof",value:8608},
{hs:"Bruchsal, Am Mantel",value:8617},
{hs:"Bruchsal, Sportzentrum",value:8618},
{hs:"K&auml;fertal, Gorxheimer Stra&szlig;e",value:8903},
{hs:"Darmstadt, Hbf",value:9001},
{hs:"Frankfurt, Hauptbahnhof",value:9003},
{hs:"Gernsheim, Bahnhof",value:9010},
{hs:"Riedstadt-Goddelau, Bahnhof",value:9012},
{hs:"Langen (Hess)",value:9015},
{hs:"Stockstadt (Rhein)",value:9032},
{hs:"Biebesheim",value:9033},
{hs:"Kaiserslautern, Hauptbahnhof",value:9035},
{hs:"Mainz, Hauptbahnhof",value:9037},
{hs:"Kerzenheim, Post",value:9058},
{hs:"Eisenberg, Marktplatz",value:9060},
{hs:"Kirchheimbolanden, Bahnhof",value:9066},
{hs:"Lautersheim, Mitte",value:9069},
{hs:"Harxheim/Pfr, Bahnhofstra&szlig;e",value:9077},
{hs:"Germersheim, Bahnhof",value:9085},
{hs:"Lingenfeld, Bahnhof",value:9087},
{hs:"Lingenfeld, Rathaus",value:9088},
{hs:"Altdorf, Kirchstra&szlig;e",value:9097},
{hs:"Altdorf, Mitte",value:9098},
{hs:"B&ouml;bingen, Ort",value:9101},
{hs:"B&ouml;bingen, Raiffeisen",value:9102},
{hs:"Gommersheim, Gasthaus Pfalz",value:9108},
{hs:"Gommersheim, Hauptstra&szlig;e",value:9110},
{hs:"Frankenstein, Bahnhof",value:9115},
{hs:"Hochspeyer, Bahnhof",value:9117},
{hs:"Guntersblum, Bahnhof",value:9120},
{hs:"Binau, Bahnhof",value:9128},
{hs:"Neckargerach, Bahnhof",value:9129},
{hs:"Bad Fr'hall-Jagstfeld",value:9130},
{hs:"Bad Rappenau, Bahnhof",value:9132},
{hs:"Karlsruhe, Hauptbahnhof",value:9150},
{hs:"Bruchsal, Bahnhof",value:9152},
{hs:"Ubstadt-Weiher, Bahnhof",value:9153},
{hs:"Weingarten (Baden)",value:9154},
{hs:"Untergrombach",value:9159},
{hs:"Graben-Neudorf, Bahnhof",value:9160},
{hs:"Bad Sch&ouml;nborn-Kronau, Bahnhof",value:9162},
{hs:"Bad Sch&ouml;nborn, S&uuml;d",value:9163},
{hs:"Neckarelz, Bahnhof",value:9180},
{hs:"Zwingenberg/Bd, Bahnhof",value:9191},
{hs:"Karlsruhe, Siemens",value:9229},
{hs:"Schwetzingen, Hebelgymnasium",value:14254},
{hs:"Studernheim, Ruchheimer Weg",value:16350},
{hs:"Studernheim, Oggersheimer Str.",value:16351},
{hs:"Waldsee, Schlicht",value:40181},
{hs:"Walldorf, Walzrute",value:40450},
{hs:"Rohrbach (Saar), Bahnhof",value:98001},
{hs:"St. Ingbert, Bahnhof",value:98283},
{hs:"Saarbr&uuml;cken, Hbf",value:98300},
{hs:"Saarbr&uuml;cken, Ost",value:98302},
{hs:"Limbach, Bahnhof",value:98383},
{hs:"Kirkel, Bahnhof",value:98398},
{hs:"Scheidt (Saar), Bahnhof",value:98624},
{hs:"Schafbr&uuml;cke, Bahnhof",value:99073},
{hs:"Rentrisch, Bahnhof",value:99075}]
